# -*- coding: utf-8 -*-
"""
由 AI 直接翻譯的遊戲文本 - 批次寫入腳本
執行方式：python scratch/do_translate_batch1.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# ============================================================
# Database_Hero.txt  （角色名稱與頭銜）
# ============================================================
write_translated("Database_Hero.txt.trans.txt", [
    "1. [TAG: Name] 以藏",
    "2. [TAG: Title] 傭兵",
    "3. [TAG: Name] 奧斯卡",
    "4. [TAG: Title] 隊長",
    "5. [TAG: Name] DANDY",
    "6. [TAG: Title] 丹迪之神",
    "7. [TAG: Name] 喬喬莉娜",
    "8. [TAG: Title] 魔導師",
    "9. [TAG: Name] 流漸",
    "10. [TAG: Title] 原型體",
    "11. [TAG: Name] 安德烈",
    "12. [TAG: Title] 大哥",
    "13. [TAG: Name] 貝爾",
    "14. [TAG: Title] 槍手",
    "15. [TAG: Name] 阿勝",
    "16. [TAG: Title] 神殿騎士",
    "17. [TAG: Name] 漆黑",
    "18. [TAG: Title] 黑子",
    "19. [TAG: Name] 阿爾夫",
])

# ============================================================
# Database_Vocab.txt  （系統語彙）
# ============================================================
write_translated("Database_Vocab.txt.trans.txt", [
    "1. [TAG: StartBattle] 出現了！！",
    "2. [TAG: PreemptiveAttack] 搶先攻擊的機會！",
    "3. [TAG: EscapeSuccess] 成功逃脫了！",
    "4. [TAG: EscapeFailure] 逃脫失敗！",
    "5. [TAG: Victory] 戰鬥勝利！",
    "6. [TAG: Defeat] 敗北了……",
    "7. [TAG: GetEXP] 的經驗值！",
    "8. [TAG: GetMoneyPart2] 到手了！",
    "9. [TAG: GetItem] 到手了！",
    "10. [TAG: NormalAttack] 的攻擊！",
    "11. [TAG: CriticalHit] 致命一擊！",
    "12. [TAG: EnemyCritical] 致命一擊！",
    "13. [TAG: DefendMessage] 正在防禦！",
    "14. [TAG: EnemyObserve] 在觀察動向……",
    "15. [TAG: EnemyBuildStrength] 在蓄積力量……",
    "16. [TAG: EnemyBurst] 自爆了！",
    "17. [TAG: EnemyEscape] 逃跑了！",
    "18. [TAG: EnemyTransform] 變身了！",
    "19. [TAG: DamageEnemy] 點傷害！",
    "20. [TAG: MissEnemy] 無法造成傷害！",
    "21. [TAG: DamageAlly] 點傷害！",
    "22. [TAG: MissAlly] 沒有受到傷害！",
    "23. [TAG: SkillFailureA] 沒有效果！",
    "24. [TAG: SkillFailureB] 毫無影響！",
    "25. [TAG: SkillFailureC] 沒有睡著！",
    "26. [TAG: AvoidPhysical] 閃避了攻擊！",
    "27. [TAG: UseItem] 使用了",
    "28. [TAG: RecoverHPMP] 回復了！",
    "29. [TAG: StatUp] 提升了！",
    "30. [TAG: StatDown] 下降了！",
    "31. [TAG: StatAbsorb] 奪取了！",
    "32. [TAG: StatSucked] 被奪走了！",
    "33. [TAG: DefenseUp] 的抵抗力提升了！",
    "34. [TAG: DefenseDown] 的抵抗力下降了！",
    "35. [TAG: LevelUp] 升級了！",
    "36. [TAG: LearnSkill] 學會了！",
    "37. [TAG: ShopA:ChoiceScreen] 「歡迎光臨」",
    "38. [TAG: ShopA:ChoiceScreenAgain] 「還有其他需要嗎？」",
    "39. [TAG: ShopA:Buy] 購買",
    "40. [TAG: ShopA:Sell] 賣出",
    "41. [TAG: ShopA:Leave] 離開",
    "42. [TAG: ShopA:BuyScreen] 「請問您要購買什麼？」",
    "43. [TAG: ShopA:HowManyToBuy] 「請問您要購買幾個？」",
    "44. [TAG: ShopA:PurchaseMade] 「感謝您的惠顧」",
    "45. [TAG: ShopA:SellScreen] 「請問您要賣出什麼？」",
    "46. [TAG: ShopA:HowManyToSell] 「請問您要賣出幾個？」",
    "47. [TAG: ShopA:SaleComplete] 「感謝您的惠顧」",
    "48. [TAG: ShopB:ChoiceScreen] 「歡迎！今天有什麼需要？」",
    "49. [TAG: ShopB:ChoiceScreenAgain] 「還有別的事嗎？」",
    "50. [TAG: ShopB:Buy] 購買",
    "51. [TAG: ShopB:Sell] 賣出",
    "52. [TAG: ShopB:Leave] 離開",
    "53. [TAG: ShopB:BuyScreen] 「要買什麼？」",
    "54. [TAG: ShopB:HowManyToBuy] 「要買幾個？」",
    "55. [TAG: ShopB:PurchaseMade] 「謝了！」",
    "56. [TAG: ShopB:SellScreen] 「要賣什麼？」",
    "57. [TAG: ShopB:HowManyToSell] 「要賣幾個？」",
    "58. [TAG: ShopB:SaleComplete] 「謝了！」",
    "59. [TAG: ShopC:ChoiceScreen] 「你好，有什麼需要嗎？」",
    "60. [TAG: ShopC:ChoiceScreenAgain] 「還有其他需要嗎？」",
    "61. [TAG: ShopC:Buy] 購買",
    "62. [TAG: ShopC:Sell] 賣出",
    "63. [TAG: ShopC:Leave] 離開",
    "64. [TAG: ShopC:BuyScreen] 「請問要買什麼？」",
    "65. [TAG: ShopC:HowManyToBuy] 「請問要買幾個？」",
    "66. [TAG: ShopC:PurchaseMade] 「非常感謝」",
    "67. [TAG: ShopC:SellScreen] 「請問要賣什麼？」",
    "68. [TAG: ShopC:HowManyToSell] 「請問要賣幾個？」",
    "69. [TAG: ShopC:SaleComplete] 「非常感謝」",
    "70. [TAG: InnA:IntroLine1a] 「住宿費用為",
    "71. [TAG: InnA:IntroLine1b] 。",
    "72. [TAG: InnA:Lodge] 住宿",
    "73. [TAG: InnA:DoNotLodge] 不住宿",
    "74. [TAG: InnB:IntroLine1a] 「一晚",
    "75. [TAG: InnB:IntroLine1b] ，",
    "76. [TAG: InnB:IntroLine2] 　要住嗎？",
    "77. [TAG: InnB:Lodge] 住宿",
    "78. [TAG: InnB:DoNotLodge] 不住宿",
    "79. [TAG: OwnedQuantity] 持有數",
    "80. [TAG: EquippedQuantity] 裝備數",
    "81. [TAG: CurrencyUnit] Ｄ",
    "82. [TAG: Fight] 戰鬥",
    "83. [TAG: Auto] 自動",
    "84. [TAG: Escape] 逃跑",
    "85. [TAG: Attack] 攻擊",
    "86. [TAG: Defend] 防禦",
    "87. [TAG: Item] 道具",
    "88. [TAG: Skill] 技能",
    "89. [TAG: Equip] 裝備",
    "90. [TAG: Save] 存檔",
    "91. [TAG: EndGame] 中斷遊戲",
    "92. [TAG: NewGame] New Game",
    "93. [TAG: Continue] Load Game",
    "94. [TAG: Quit] End Game",
    "95. [TAG: Level] 等級",
    "96. [TAG: HP] ＨＰ",
    "97. [TAG: MP] ＭＰ",
    "98. [TAG: NormalState] 正常",
    "99. [TAG: EXPShort] Ｅ",
    "100. [TAG: LevelShort] Ｌ",
    "101. [TAG: HPShort] Ｈ",
    "102. [TAG: MPShort] Ｍ",
    "103. [TAG: MPCost] 消耗ＭＰ",
    "104. [TAG: Offense] 攻擊力",
    "105. [TAG: Defense] 防禦力",
    "106. [TAG: Mind] 精神力",
    "107. [TAG: Agility] 敏捷性",
    "108. [TAG: Arms] 武器",
    "109. [TAG: Shield] 盾牌",
    "110. [TAG: Armor] 鎧甲",
    "111. [TAG: Helmet] 頭盔",
    "112. [TAG: Other] 飾品",
    "113. [TAG: ChooseSaveFile] 要存入哪個檔案？",
    "114. [TAG: ChooseLoadFile] 要讀取哪個檔案？",
    "115. [TAG: File] File",
    "116. [TAG: QuitConfirm] 確定要中斷遊戲嗎？",
    "117. [TAG: QuitYes] Yes",
    "118. [TAG: QuitNo] No",
])

print("\n=== 批次 1（Hero、Vocab）完成 ===")
