# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0005 (奧斯卡宅邸)"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

write_translated("Map0005.txt.trans.txt", [
    "1. [MARKER: Message] [FACE: 顔002, 2, Right, Flip Horizontal] 奧斯卡「",
    "已經去公會了嗎？",
    "2. [MARKER: Message] [FACE: イゾウ, 1, Left, Normal] 以藏「",
    "啊……",
    "3. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "還沒去啊。",
    "去公會拿了委託合約書",
    "再過來吧。",
    "4. [MARKER: Message] [FACE: 顔002, 2, Right, Flip Horizontal] 奧斯卡「",
    "這次的委託你也接下了嗎。",
    "幫了我大忙。",
    "5. [MARKER: Message] [FACE: イゾウ, 1, Left, Normal] 以藏「",
    "那倒無所謂，但是……\\.",
    "上次任務的酬勞給我啊。",
    "6. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "好好好，\\. 等這次任務成功再給你。",
    "7. [MARKER: Message] [FACE: Erase] 以藏「",
    "・\\.・\\.・\\.・\\.・\\S[4]・……現在就給。",
    "8. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "……１００００Ｄ。",
    "9. [MARKER: Message] [FACE: Erase] 以藏「",
    "\\. ……什麼？",
    "10. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "這次連上次一起，給你１００００Ｄ。",
    "",
    "怎樣？",
    "11. [MARKER: Message] [FACE: Erase] 以藏「",
    "・\\.・\\.・\\.・\\.・\\.・\\.・……認真的？",
    "12. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "當然。\\. 那麼，話不多說，這次往\\C[7]英國\\C[0]出發。",
    "任務內容是調查英國無敵艦隊",
    "『\\C[5]伊莉莎白八號\\C[0]』。",
    "13. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "這次我也一起去。",
    "首先，前往有船開往英國的\\C[8]艾爾米\\C[0]。",
    "14. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "記清楚了，艾爾米在北邊。",
    "15. [MARKER: Message] [FACE: Erase] 女僕「",
    "你知道里德・艾倫嗎？",
    "16. [MARKER: Message] [FACE: Erase] 女僕「",
    "唔～……那算了。",
    "17. [MARKER: Message] [FACE: Erase] 女僕「",
    "說他現在來到了這個凡爾賽呢。",
    "18. [MARKER: Message] [FACE: Erase] 女僕「",
    "……他在幹嘛呢？",
    "19. [MARKER: Message] [FACE: Erase] 女僕「",
    "那麼，請多保重。",
    "以藏大人，\\. 艾爾米在北邊喔。",
    "20. [MARKER: Message] [FACE: Erase] 女僕「",
    "你知道里德・艾倫嗎？",
    "21. [MARKER: Message] [FACE: Erase] 女僕「",
    "唔～……那算了。",
    "22. [MARKER: Message] [FACE: Erase] 女僕「",
    "說他現在來到了這個凡爾賽呢。",
    "23. [MARKER: Message] [FACE: Erase] 女僕「",
    "……他在幹嘛呢？",
    "24. [MARKER: Message] [FACE: Erase] 女僕「",
    "奧斯卡大人，您回來了。",
    "25. [MARKER: Message] [FACE: Erase] 女僕「",
    "奧斯卡大人，您回來了。",
    "26. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "啊，聽說你見過艾倫……",
    "是真的嗎？",
    "27. [MARKER: Message] [FACE: Erase] 女僕「",
    "是的，前幾天買完東西回來時匆匆一瞥……",
    "28. [MARKER: Message] [FACE: Erase] 女僕「",
    "好像是巴士底監獄入口",
    "往西方向。",
    "29. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "這樣就夠了。",
    "做得好。",
    "30. [MARKER: Message] [FACE: Erase] 女僕「",
    "謝謝您。",
    "請多保重……",
    "31. [MARKER: Message] [FACE: Erase] 女僕「",
    "是巴士底監獄入口往西方向。",
    "32. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "33. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "……什麼事？",
    "34. [MARKER: Message] [FACE: Erase] 女僕「",
    "請帶著這個。",
    "35. [MARKER: Message] [FACE: Erase] ",
    "　　　　　　　　獲得了導航儀！！",
    "36. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "這是……？",
    "37. [MARKER: Message] [FACE: Erase] 女僕「",
    "能自動計算目前位置的",
    "導航機器。",
    "38. [MARKER: Message] [FACE: Erase] 女僕「",
    "也附有簡化版世界地圖，",
    "非常好用喔$g",
    "39. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "……這東西你從哪弄來的……",
    "40. [MARKER: Message] [FACE: Erase] 女僕「",
    "細節就別在意了……",
    "41. [MARKER: Message] [FACE: Erase] 女僕「",
    "啊，\\| 還有，只能在城鎮外使用，",
    "請注意。",
    "42. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "43. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "44. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "45. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "46. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "47. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "48. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "49. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "50. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "51. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "52. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
    "53. [MARKER: Message] [FACE: Erase] ＊「",
    "請稍候！",
])

print("Map0005 done.")
