# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0006 (法國城堡) + Map0007 (艾爾米港鎮)"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# ─────────────────────────────────────────────
# Map0006  (法國城堡 / 英國艦隊調查)
# ─────────────────────────────────────────────
write_translated("Map0006.txt.trans.txt", [
    "1. [MARKER: Message] 受付「",
    "目前沒有前往艾爾米的船班預定。",
    "請稍後再來。",
    "2. [MARKER: Message] 士兵「",
    "前方請止步……",
    "3. [MARKER: Message] 奧斯卡「",
    "有點可疑……有什麼蹊蹺……",
    "4. [MARKER: Message] 以藏「",
    "背刺——！！",
    "5. [MARKER: Message] 士兵「",
    "哇！！！",
    "6. [MARKER: Message] 奧斯卡「",
    "……那是雙刃劍喔……",
    "7. [MARKER: Message] 以藏「",
    "・\\.・\\.・\\.是你想太多了。",
    "8. [MARKER: Message] 士兵「",
    "……………………………………",
    "9. [MARKER: Message] 安德烈「",
    "大哥我哪裡都跟$g",
    "10. [MARKER: Message] 伊莉莎白「",
    "這裡所有的東西，都是新日本的",
    "「\\N[5]」親手建造的。",
    "11. [MARKER: Message] 伊莉莎白「",
    "他設計了城堡……甚至連我國的兵器",
    "都是他設計的。",
    "12. [MARKER: Message] 路易十三世「",
    "我是國王。",
    "13. [MARKER: Message] 男子「",
    "我打算從這裡前往北邊的英國城鎮，",
    "再去印度。",
    "14. [MARKER: Message] 鋼琴師「",
    "哎？果然又見面了！",
    "15. [MARKER: Message] 鋼琴師「",
    "我打算從北邊的英國城鎮",
    "前往印度。",
    "16. [MARKER: Message] 奧斯卡「",
    "等等，以藏！",
    "伊莉莎白八號應該就在城內！！",
    "17. [MARKER: Message] 奧斯卡「",
    "等等，以藏！",
    "伊莉莎白八號應該就在城內！！",
    "18. [MARKER: Message] ？「",
    "等著……別以為能活著出去！！",
    "19. [MARKER: Message] 以藏「",
    "……？",
    "20. [MARKER: Message] 士兵「",
    "你用背刺騙我，把我殺了！",
    "21. [MARKER: Message] 奧斯卡「",
    "果然是雙刃……",
    "22. [MARKER: Message] 以藏「",
    "是你想太多了……",
    "23. [MARKER: Message] 士兵「",
    "真……遺憾……",
    "24. [MARKER: Message] 以藏「",
    "……走吧……",
    "25. [MARKER: Message] ？「",
    "等著……別以為能活著出去！！",
    "26. [MARKER: Message] 以藏「",
    "……？",
    "27. [MARKER: Message] 士兵「",
    "你用背刺騙我，把我殺了！",
    "28. [MARKER: Message] 奧斯卡「",
    "果然是雙刃……",
    "29. [MARKER: Message] 以藏「",
    "是你想太多了……",
    "30. [MARKER: Message] 士兵「",
    "真……遺憾……",
    "31. [MARKER: Message] 以藏「",
    "……走吧……",
    "32. [MARKER: Message] 男子「",
    "哎呀，聽說船班好像延誤了。",
    "33. [MARKER: Message] ",
    "　　　　　　　前方，英國碼頭",
    "34. [MARKER: Message] 士兵「",
    "「\\N[5]」據說是世界第一的設計工程師。",
    "35. [MARKER: Message] 士兵「",
    "而他的故鄉「新日本」",
    "據說也全由他一手建造。",
    "36. [MARKER: Message] 士兵「",
    "因此，整個國家都成為了機械都市……",
    "37. [MARKER: Message] 大臣「",
    "讓別國人設計城堡……",
    "我王到底在想什麼……",
    "38. [MARKER: Message] 商人「",
    "現在英國正值戰事，",
    "所以進不去呢……",
    "好可怕啊……",
])

# ─────────────────────────────────────────────
# Map0007  (艾爾米港鎮)
# ─────────────────────────────────────────────
write_translated("Map0007.txt.trans.txt", [
    "1. [MARKER: Message] 　　　　　　　　　徵募工讀生",
    "　　　　　　充滿幹勁者，即刻報名。",
    "　　　　　　　１８歲以上者，歡迎！",
    "　　　　　　　　　　　　　　　　　　　　艾爾米酒吧",
    "2. [MARKER: Message] 詳細部分被塗鴉蓋掉了，無法閱讀。",
    "大概是這個城鎮的孩子們幹的。",
    "3. [MARKER: Message] 商人「",
    "本店販賣各種道具。",
    "4. [MARKER: Message] 商人「",
    "謝謝惠顧，歡迎再來。",
    "5. [MARKER: Message] ",
    "　　　　　　　　　艾爾米船舶中心",
    "6. [MARKER: Message] 戰士「",
    "好想吃東西——！！！",
    "7. [MARKER: Message] 以藏「",
    "……我也好想吃——！！",
    "8. [MARKER: Message] 奧斯卡「",
    "…………………………",
    "9. [MARKER: Message] 戰士「",
    "好想吃東西——！！！",
    "10. [MARKER: Message] 奧斯卡「",
    "不，我現在還不想吃。",
    "11. [MARKER: Message] 戰士「",
    "你真是太掃興了……",
    "12. [MARKER: Message] 戰士「",
    "好想吃東西——！！！",
    "13. [MARKER: Message] 喬喬莉娜「",
    "不用那麼強調，想吃就直接吃啊$g",
    "14. [MARKER: Message] 戰士「",
    "是……是的……",
    "15. [MARKER: Message] 以藏「",
    "…………………………………………",
    "16. [MARKER: Message] 安德烈「",
    "我又不是商人……",
    "17. [MARKER: Message] ＊「",
    "媽媽，我想要這個～",
    "18. [MARKER: Message] ＊「",
    "好好好，等一下買給你喔。",
    "19. [MARKER: Message] 大叔「",
    "那邊常常出沒的海鷗，",
    "是這個地區才有的「莫西干海鷗」。",
    "20. [MARKER: Message] 大叔「",
    "請別誤以為是雞在飛。",
    "21. [MARKER: Message] 少女「",
    "歡迎來到艾爾米！",
    "22. [MARKER: Message] 奧斯卡「",
    "我想搭船……",
    "23. [MARKER: Message] 少女「",
    "的話，從這裡往右走，",
    "到底再左轉……",
    "24. [MARKER: Message] 少女「",
    "前方就是船舶中心，",
    "請從那裡搭乘。",
    "25. [MARKER: Message] 奧斯卡「",
    "……謝謝。",
    "26. [MARKER: Message] 少女「",
    "兩位一起旅行嗎？",
    "27. [MARKER: Message] 少女「",
    "歡迎來到艾爾米！",
    "28. [MARKER: Message] 雷比特「",
    "糟了！被發現了！！",
    "我在告示上塗鴉的事，是秘密喔！",
    "29. [MARKER: Message] 雷比特「",
    "咦，還有事嗎？",
    "30. [MARKER: Message] 男孩「",
    "今天雷比特那傢伙不見了……",
    "是躲在哪裡了嗎？",
    "31. [MARKER: Message] 女孩「",
    "聽說雷比特在酒吧的告示上塗鴉了！",
    "32. [MARKER: Message] 船員「",
    "哎，你妨礙我工作了！！",
    "……快點把貨物裝上去！！",
    "33. [MARKER: Message] \\S[5]",
    "　　　　　以藏一行人出發前往英國……\\|\\|\\^",
    "34. [MARKER: Message] 奧斯卡「",
    "以藏，我們有自己的船，",
    "不必搭這艘吧。",
    "35. [MARKER: Message] 以藏「",
    "啊……\\.也對……",
    "36. [MARKER: Message] 以藏「",
    "與其來這種地方，不如去凡爾賽。凡爾賽。",
    "37. [MARKER: Message] 奧斯卡「",
    "去巴士底吧……",
    "38. [MARKER: Message] 男子「",
    "請出示船票。",
    "39. [MARKER: Message] 以藏「",
    "啊，還沒買……",
    "40. [MARKER: Message] 奧斯卡「",
    "回到船舶中心買吧。",
    "41. [MARKER: Message] 男子「",
    "請出示船票。",
    "42. [MARKER: Message] 以藏「",
    "這個可以嗎？",
    "43. [MARKER: Message] 男子「",
    "確認無誤。",
    "請通過。",
    "44. [MARKER: Message] 男子「",
    "祝您旅途愉快。",
    "45. [MARKER: Message] 男子「",
    "祝您旅途愉快。",
    "46. [MARKER: Message] 男子「",
    "目前沒有前往英國的船班。",
    "47. [MARKER: Message] 男子「",
    "目前因戰爭關係，",
    "無法前往英國入港。",
    "請改走其他路線。",
    "48. [MARKER: Message] 男子「",
    "請出示船票。",
    "49. [MARKER: Message] 以藏「",
    "啊，還沒買……",
    "50. [MARKER: Message] 奧斯卡「",
    "回到船舶中心買吧。",
    "51. [MARKER: Message] 男子「",
    "請出示船票。",
    "52. [MARKER: Message] 以藏「",
    "這個可以嗎？",
    "53. [MARKER: Message] 男子「",
    "確認無誤。",
    "請通過。",
    "54. [MARKER: Message] 男子「",
    "祝您旅途愉快。",
    "55. [MARKER: Message] 船員「",
    "啊，這艘船目前",
    "沒有出發計畫喔。",
    "去隔壁那艘吧。",
    "56. [MARKER: Message] 商人「",
    "歡迎光臨。",
    "本店販賣英國進口商品。",
    "57. [MARKER: Message] 商人「",
    "謝謝，歡迎再來！",
    "58. [MARKER: Message] 劍客「",
    "這個陣容，不愧是英國貨。",
    "我也想去英國了。",
    "59. [MARKER: Message] 以藏「",
    "哦，裡面有東西耶。",
    "60. [MARKER: Message] [FACE: Erase] ",
    "　　　　　　　　　　獲得了蘋果！！",
    "61. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "\\S[3]…………",
    "好寒酸啊……",
    "62. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "裡面有東西……",
    "63. [MARKER: Message] [FACE: Erase] ",
    "　　　　　　　　　　獲得了蘋果！！",
    "64. [MARKER: Message] [FACE: Erase] 以藏「",
    "哦，裡面有東西耶。",
    "65. [MARKER: Message] [FACE: Erase] ",
    "　　　　　　　　　　獲得了蘋果！！",
    "66. [MARKER: Message] [FACE: Erase] 喬喬莉娜「",
    "真寒酸呢……$g",
    "67. [MARKER: Message] [FACE: Erase] 男子「",
    "祝您旅途愉快。",
    "68. [MARKER: Message] [FACE: Erase] 男子「",
    "目前沒有前往英國的船班。",
    "69. [MARKER: Message] [FACE: Erase] 男子「",
    "目前因戰爭關係，",
    "無法前往英國入港。",
    "請改走其他路線。",
])

print("Map0006 / Map0007 done.")
