# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0009, Map0010, Map0011, Map0012"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0009 (艾爾米酒吧)
write_translated("Map0009.txt.trans.txt", [
    "1. [MARKER: Message] 老闆「",
    "喔？要喝點什麼嗎？",
    "2. [MARKER: Message] 以藏「",
    "哦哦哦哦哦哦！！！",
    "熱血沸騰——！！",
    "3. [MARKER: Message] 奧斯卡「",
    "嗯，還不錯嘛……",
    "4. [MARKER: Message] 以藏「",
    "果然還是烏龍茶啊。",
    "5. [MARKER: Message] 以藏「",
    "……果然不是在酒吧喝的東西……",
    "6. [MARKER: Message] 奧斯卡「",
    "其他客人都用奇怪的眼神看你……",
    "7. [MARKER: Message] 老闆「",
    "在工讀徵人告示上塗鴉？",
    "8. [MARKER: Message] 老闆「",
    "反正肯定是雷比特那傢伙……",
    "回來一定好好問問他。",
    "9. [MARKER: Message] 以藏「",
    "原來是你兒子……",
    "10. [MARKER: Message] 老闆「",
    "要喝點什麼嗎？",
    "11. [MARKER: Message] 奧斯卡「",
    "現在沒空喝，就不打擾了……",
    "12. [MARKER: Message] 鋼琴師「",
    "要彈首曲子嗎？",
    "13. [MARKER: Message] 鋼琴師「",
    "……那……好的……",
    "14. [MARKER: Message] 鋼琴師「",
    "……這樣啊。",
    "15. [MARKER: Message] 鋼琴師「",
    "咦？你聽說我不是這裡的專屬鋼琴師？",
    "16. [MARKER: Message] 鋼琴師「",
    "是的，我確實是一邊修行鋼琴技藝，",
    "一邊環遊世界旅行。",
    "17. [MARKER: Message] 鋼琴師「",
    "這裡我也快要離開了。",
    "或許我們還會再見面呢。",
    "18. [MARKER: Message] 鋼琴師「",
    "要彈首曲子嗎？",
    "19. [MARKER: Message] 鋼琴師「",
    "……那……好的……",
    "20. [MARKER: Message] 鋼琴師「",
    "……這樣啊。",
    "21. [MARKER: Message] 大叔「",
    "現在來了個不錯的鋼琴師喔。",
    "22. [MARKER: Message] 大叔「",
    "嗯？說他不是這裡的專屬？",
    "23. [MARKER: Message] 大叔「",
    "看來像是個流浪鋼琴師喔。",
    "去問問本人吧？",
    "24. [MARKER: Message] 大叔「",
    "喝得不夠……",
    "25. [MARKER: Message] 大叔「",
    "以前這裡也很有活力的……",
    "現在年輕人都跑去都市了……",
])

# Map0010 (小商店)
write_translated("Map0010.txt.trans.txt", [
    "1. [MARKER: Message] 大叔「",
    "謝謝，下次再來。",
    "2. [MARKER: Message] 大叔「",
    "是來逛逛的嗎。",
    "3. [MARKER: Message] 旅人「",
    "真是個蕭條的地方……",
])

# Map0011 (DANDY & 喬喬莉娜 vs 阿拉斯托爾)
write_translated("Map0011.txt.trans.txt", [
    "1. [MARKER: Message] DANDY「",
    "\\S[2]……這裡是……",
    "2. [MARKER: Message] 阿拉斯托爾「",
    "……多了個多餘的……",
    "3. [MARKER: Message] DANDY「",
    "你是誰！！？",
    "4. [MARKER: Message] 阿拉斯托爾「",
    "吾乃阿拉斯托爾……",
    "『DANDY』，\\. 吾是來取你性命的。",
    "5. [MARKER: Message] DANDY「",
    "\\S[2]哦……",
    "6. [MARKER: Message] 喬喬莉娜「",
    "傷害DANDY大人，這個我絕不允許$g",
    "7. [MARKER: Message] 阿拉斯托爾「",
    "\\S[2]……咯咯咯……",
    "8. [MARKER: Message] 阿拉斯托爾「",
    "\\S[1]女人，妳究竟看上這傢伙哪裡了？\\.",
    "這個男人『DANDY』，",
    "並不是妳所想的那種存在……",
    "9. [MARKER: Message] 喬喬莉娜「",
    "\\S[2]……………",
    "10. [MARKER: Message] 阿拉斯托爾「",
    "這個男人，是與這個世界不同的住民……",
    "他的世界滅亡之時，逃到了這個世界，",
    "也就是說，是個敗者……",
    "11. [MARKER: Message] 阿拉斯托爾「",
    "而且他並非人類。",
    "是那個世界的工程師所製造的精巧人偶……",
    "話說，看一眼不就知道了嗎？",
    "12. [MARKER: Message] DANDY「",
    "\\S[2]…………",
    "13. [MARKER: Message] 喬喬莉娜「",
    "這種事……我從一開始就知道了……",
    "14. [MARKER: Message] 喬喬莉娜「",
    "但是，我是為了瑪麗・安東尼的",
    "不死實驗而生的孩子……\\.",
    "我是作為道具而誕生的存在……",
    "15. [MARKER: Message] 喬喬莉娜「",
    "DANDY大人是誰造的，我根本不在乎！\\.",
    "\\S[2]只要能與懂得我相同痛苦的人",
    "在一起就夠了……",
    "16. [MARKER: Message] DANDY「",
    "\\S[2]喬喬莉娜殿……",
    "17. [MARKER: Message] 喬喬莉娜「",
    "還有你……揭露人家男友的過去，",
    "想藉此撩妹，真是太卑鄙了……",
    "18. [MARKER: Message] 喬喬莉娜「",
    "\\C[5]就讓本小姐，喬喬莉娜・安東瓦內特",
    "把你化為灰燼$g$g$g",
    "19. [MARKER: Message] 阿拉斯托爾「",
    "\\S[2]我並沒有在撩妹……\\.",
    "也罷……\\S[1]就用那份愛，\\.死也要貫徹到底！！",
    "20. [MARKER: Message] 喬喬莉娜「",
    "出發，DANDY大人！！！$g$g",
    "21. [MARKER: Message] DANDY「",
    "好——！！！",
])

# Map0012 (港口船邊)
write_translated("Map0012.txt.trans.txt", [
    "1. [MARKER: Message] 老爺爺「",
    "這裡是英國。",
    "2. [MARKER: Message] 男子「",
    "大海……那是男人的浪漫……",
    "",
    "\\.\\.……你也這樣覺得吧？",
    "3. [MARKER: Message] 以藏「",
    "……是的，我這樣覺得。",
    "4. [MARKER: Message] DANDY「",
    "男人的浪漫就是追求丹迪！！",
    "5. [MARKER: Message] 喬喬莉娜「",
    "DANDY大人，好帥$g$g",
    "6. [MARKER: Message] 男子「",
    "\\S[2]…………",
    "7. [MARKER: Message] 奧斯卡「",
    "以藏，我們有自己的船，",
    "不必搭這艘吧。",
    "8. [MARKER: Message] 以藏「",
    "啊……\\.也對……",
    "9. [MARKER: Message] 以藏「",
    "與其來這種地方，不如去凡爾賽。凡爾賽。",
    "10. [MARKER: Message] 奧斯卡「",
    "去巴士底吧……",
])

print("Map0009-0012 done.")
