# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0021, Map0022, Map0025, Map0026"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0021 (英國高台旅館)
write_translated("Map0021.txt.trans.txt", [
    "1. [MARKER: Message] 少女「",
    "歡迎光臨。請問您要住宿嗎？",
    "2. [MARKER: Message] 少女「",
    "感謝您的光臨！",
    "歡迎再次蒞臨。",
    "3. [MARKER: Message] 少女「",
    "下次歡迎再度利用。",
    "4. [MARKER: Message] 男子「",
    "從這裡還可以看到海，",
    "景色真好啊！！",
])

# Map0022 (民宅)
write_translated("Map0022.txt.trans.txt", [
    "1. [MARKER: Message] 婆婆「",
    "…………",
    "2. [MARKER: Message] 婆婆「",
    "擅自闖入人家家裡，",
    "膽子還真不小啊……",
])

# Map0025 (英國城堡前船務中心)
write_translated("Map0025.txt.trans.txt", [
    "1. [MARKER: Message] 受付「",
    "歡迎光臨。",
    "請問您要購買前往印度的船票嗎？",
    "2. [MARKER: Message] \\$受付「",
    "船票為１００Ｄ。",
    "請問可以嗎？",
    "3. [MARKER: Message] 受付「",
    "感謝您的惠顧。",
    "請收好您的船票。",
    "4. [MARKER: Message] ",
    "　　　　　　　獲得了乘船票！！",
    "5. [MARKER: Message] 受付「",
    "即將出發。",
    "請快些前往。",
    "6. [MARKER: Message] 受付「",
    "不好意思……您的錢好像不夠……",
    "7. [MARKER: Message] 受付「",
    "歡迎再次蒞臨。",
    "8. [MARKER: Message] 受付「",
    "歡迎再次蒞臨。",
    "9. [MARKER: Message] 受付「",
    "歡迎再次蒞臨。",
    "10. [MARKER: Message] 受付「",
    "您似乎已經持有船票了。\\.",
    "感謝您的惠顧。",
    "11. [MARKER: Message] 受付「",
    "目前英國出港受到管制，\\.",
    "一般乘客禁止搭乘。",
    "非常抱歉……",
])

# Map0026 (印度城鎮)
write_translated("Map0026.txt.trans.txt", [
    "1. [MARKER: Message] 男子「",
    "歡迎來到印度共和國。",
    "正面看到的，是統御此地的宗教",
    "「印度教」的總本山寺院。",
    "2. [MARKER: Message] 男子「",
    "今天也好熱啊～",
    "3. [MARKER: Message] 女子「",
    "在這印度，由於地面土質的關係，",
    "水患很多呢。",
    "4. [MARKER: Message] 女子「",
    "所以很多家庭才蓋成兩層樓。",
    "不是為了擺闊，喔。",
    "5. [MARKER: Message] 男子「",
    "前方就是「印度寺」。",
    "要不要去參拜看看？",
    "6. [MARKER: Message] 大叔「",
    "剛才那草叢裡，好像閃了一下光……",
    "7. [MARKER: Message] 大叔「",
    "哎，竟然掉著一顆天龍石……",
    "\\S[2]唔唔……\\S[1]早點撿起來就好了……",
    "8. [MARKER: Message] ",
    "　　　　　　　撿到了天龍石！！",
    "9. [MARKER: Message] 神父「",
    "我來到這裡，是為了傳播「基督教」……",
    "10. [MARKER: Message] 神父「",
    "但「印度教」規模太大，",
    "根本輪不到我說教……",
    "慘啊……",
    "11. [MARKER: Message] 男孩「",
    "我正在進行湖面跳板挑戰呢。",
    "12. [MARKER: Message] 男孩「",
    "如果能在８秒內抵達對岸，",
    "就給你好東西喔。",
    "13. [MARKER: Message] 男孩「",
    "順帶一提，過法是：木板漂過來時，",
    "在眼前按確定鍵。",
    "……要試試看嗎？",
    "14. [MARKER: Message] 男孩「",
    "那，開始囉……",
    "15. [MARKER: Message] 男孩「",
    "\\S[3]預備——……",
    "",
    "\\|\\>砰！！！\\<\\^",
    "16. [MARKER: Message] 男孩「",
    "哼，沒意思。",
    "17. [MARKER: Message] 男孩「",
    "要放棄了嗎？",
    "18. [MARKER: Message] 男孩「",
    "那就下次成功吧。",
    "19. [MARKER: Message] 男孩「",
    "那麼，加油吧！",
    "20. [MARKER: Message] 男孩「",
    "人不可貌相啊～……",
    "21. [MARKER: Message] 以藏「",
    "是個早熟的孩子。",
    "22. [MARKER: Message] 男孩「",
    "人不可貌相啊～……",
    "23. [MARKER: Message] 奧斯卡「",
    "什麼嘛……",
    "24. [MARKER: Message] 男孩「",
    "要放棄了嗎？",
    "25. [MARKER: Message] 男孩「",
    "那就下次成功吧。",
    "26. [MARKER: Message] 男孩「",
    "那麼，加油吧！",
    "27. [MARKER: Message] 男孩「",
    "要放棄了嗎？",
    "28. [MARKER: Message] 男孩「",
    "那就下次成功吧。",
    "29. [MARKER: Message] 男孩「",
    "那麼，加油吧！",
    "30. [MARKER: Message] 女孩「",
    "我們正在玩好玩的遊戲喔～",
    "想玩的話，去跟那邊的哥哥說吧。",
    "31. [MARKER: Message] 女孩「",
    "哇——成功了！！",
    "32. [MARKER: Message] 女孩「",
    "那就按照約定，把道具給你吧。",
    "33. [MARKER: Message] ",
    "　　　　　　　獲得了電晶體！！",
    "34. [MARKER: Message] 奧斯卡「",
    "這要用來做什麼？",
    "35. [MARKER: Message] 以藏「",
    "\\S[3]……是詐騙……",
    "36. [MARKER: Message] 女孩「",
    "叔叔已經過關了，",
    "不能再玩了喔。",
    "37. [MARKER: Message] 以藏「",
    "誰叫叔叔，你這小鬼。",
    "38. [MARKER: Message] 女孩「",
    "姊姊已經過關了，",
    "不能再玩了喔。",
    "39. [MARKER: Message] 男孩「",
    "\\S[2]時間到——！！",
    "40. [MARKER: Message] 男孩「",
    "歡迎再挑戰喔。",
    "41. [MARKER: Message] 男子「",
    "那邊正在玩湖面跳板……",
    "還挺難的呢。",
    "42. [MARKER: Message] 男子「",
    "木板漂過來，有時候能跳上去，",
    "有時候又跳不上去……",
    "43. [MARKER: Message] 男子「",
    "往東走就是擁有世界最多人口的",
    "「中國」喔。",
    "44. [MARKER: Message] 男子「",
    "聽說附近的河川上停著",
    "巨大的船隻……",
    "45. [MARKER: Message] 印度男「",
    "今天的印度天氣真好！",
    "牛也很精神……",
    "我真幸福啊！",
    "46. [MARKER: Message] 時髦印度人「",
    "您喝過奶茶了嗎？",
    "這可是印度引以為傲的最強飲料！",
    "47. [MARKER: Message] 大叔「",
    "這裡原本是個極度貧困的國家，",
    "要不是義賊里德・艾倫給了我們錢，",
    "現在恐怕還是餓殍遍野的貧國……",
    "48. [MARKER: Message] ",
    "　　　　　　　　　什麼都沒有……",
    "49. [MARKER: Message] ",
    "　　　　　　　　　什麼都沒有……",
])

print("Map0021-0026 done.")
