# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0027 (埃及), Map0028 (新日本機械都市), Map0029 (中國城鎮)"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0027 (埃及 - 喬喬莉娜加入)
write_translated("Map0027.txt.trans.txt", [
    "1. [MARKER: Message] 男子「",
    "這裡還在施工中呢。",
    "2. [MARKER: Message] 大叔「",
    "唔……材料好像還不夠……",
    "3. [MARKER: Message] 女子「",
    "沒事的人請不要進來喔$g",
    "4. [MARKER: Message] 女子「",
    "有什麼事嗎$g",
    "5. [MARKER: Message] 以藏「",
    "妳，會「潛入」術嗎？",
    "6. [MARKER: Message] 女子「",
    "會喔$g",
    "7. [MARKER: Message] 以藏「",
    "\\S[2]那麼，我有事想拜託妳……\\|\\^",
    "8. [MARKER: Message] 女子「",
    "不$g",
    "9. [MARKER: Message] 以藏「",
    "\\S[2]……啥？",
    "10. [MARKER: Message] 女子「",
    "我只聽丹迪風格的人說話喔$g",
    "11. [MARKER: Message] 以藏「",
    "\\S[3]……哦……",
    "12. [MARKER: Message] 以藏「",
    "那妳是說，我沒有丹迪風格囉。",
    "13. [MARKER: Message] 女子「",
    "對啊$g",
    "就是這樣$g",
    "14. [MARKER: Message] 以藏「",
    "跟這種蠢女人糾纏沒意義……",
    "\\S[2]走吧，奧斯卡……",
    "15. [MARKER: Message] 女子「",
    "我才不蠢$g",
    "16. [MARKER: Message] 女子「",
    "\\S[3]……這……這個人好有丹迪風格！！！",
    "17. [MARKER: Message] 喬喬莉娜「",
    "我叫喬喬莉娜$g",
    "我要跟您一輩子！！$g$g",
    "18. [MARKER: Message] ",
    "　　　　喬喬莉娜強行跟上了！",
    "19. [MARKER: Message] 奧斯卡「",
    "\\S[4]……\\S[2]……先……先回新日本吧……",
    "20. [MARKER: Message] 奧斯卡「",
    "等等，以藏！！",
    "找到了能用「潛入」術的魔法師，",
    "就這樣放棄嗎……",
    "21. [MARKER: Message] 以藏「",
    "\\S[2]要讓那個蠢女人聽話，",
    "\\>只有帶個有丹迪風格的人來才行。\\<",
    "22. [MARKER: Message] 奧斯卡「",
    "……你想帶誰來……？",
    "23. [MARKER: Message] 以藏「",
    "\\S[3]……這個嘛……",
    "24. [MARKER: Message] 老人「",
    "此國四面為沙漠所圍，",
    "水是國家的珍寶啊。",
    "25. [MARKER: Message] 老人「",
    "所以，糟蹋水資源",
    "是絕不被允許的！！",
    "26. [MARKER: Message] 旅人「",
    "澳洲在新日本的南邊喔。",
    "27. [MARKER: Message] 以藏「",
    "你怎麼知道？",
    "28. [MARKER: Message] 旅人「",
    "因為我從澳洲來嘛。",
    "29. [MARKER: Message] 旅人「",
    "差不多該回澳洲了嗎？",
    "30. [MARKER: Message] 女子「",
    "我丈夫是木匠。",
    "今天也應該在南邊建造港口。",
    "31. [MARKER: Message] 女子「",
    "如果港口建好了，這裡也會變得更繁榮吧。",
    "32. [MARKER: Message] ",
    "　　　　　　喬喬莉娜魔法診療所",
    "33. [MARKER: Message] ",
    "　　　　　　　　　歡迎光臨！！",
    "　　　　歡迎來到沙漠之都「埃及」！！",
    "34. [MARKER: Message] 女子「",
    "\\S[3]丹迪之神……",
    "\\S[2]肯定非常有丹迪風格吧。",
    "35. [MARKER: Message] 女子「",
    "你在找有丹迪風格的人嗎？",
    "36. [MARKER: Message] 女子「",
    "那就往東南方的「澳洲」去吧。",
    "據說丹迪之神就在那裡。",
    "37. [MARKER: Message] 女子「",
    "難道說，這位就是丹迪之神……！？",
    "\\S[3]……啊……太棒了……！",
    "38. [MARKER: Message] 以藏「",
    "\\S[3]……………………………………………",
    "39. [MARKER: Message] ",
    "　　　　　　喬喬莉娜魔法診療所",
    "40. [MARKER: Message] 瑪麗・安東尼「",
    "你以為能白白了事嗎！？",
    "41. [MARKER: Message] 喬喬莉娜「",
    "真是煩死了……$g",
    "42. [MARKER: Message] ",
    "　　　　那個時候……安德烈……",
    "43. [MARKER: Message] ",
    "　　　　　　　　\\S[2]迷路了……",
    "44. [MARKER: Message] 安德烈「",
    "……雖然追著以藏的氣息來了……",
    "這裡到底……是哪裡……？",
    "45. [MARKER: Message] 安德烈「",
    "總之……不走走看的話",
    "也找不到以藏啊……",
])

# Map0028 (新日本 - 接受任務)
write_translated("Map0028.txt.trans.txt", [
    "1. [MARKER: Message] 奧斯卡「",
    "\\N[5]在哪裡？",
    "2. [MARKER: Message] 男子「",
    "你們認識\\N[5]！？",
    "3. [MARKER: Message] 奧斯卡「",
    "嗯，是熟人。",
    "4. [MARKER: Message] 以藏「",
    "\\S[3]…………………………",
    "5. [MARKER: Message] 男子「",
    "你們是從西邊來的吧？",
    "6. [MARKER: Message] 奧斯卡「",
    "嗯，從凡爾賽來的。",
    "7. [MARKER: Message] 男子「",
    "拜託你們！",
    "請幫我們帶一位魔法師來！",
    "8. [MARKER: Message] 以藏「",
    "為什麼需要魔法師……？",
    "9. [MARKER: Message] 男子「",
    "\\N[5]被數位病毒感染了。",
    "10. [MARKER: Message] 以藏「",
    "\\S[4]……數……位……病……毒？",
    "11. [MARKER: Message] 男子「",
    "這裡，新日本，是由\\N[5]建造的",
    "電腦全面管理的國家。",
    "12. [MARKER: Message] 男子「",
    "……然而某天，主電腦",
    "「C550-D」感染了病毒，",
    "變得一塌糊塗……",
    "13. [MARKER: Message] 男子「",
    "整個國家瀕臨崩潰……",
    "14. [MARKER: Message] 男子「",
    "於是\\N[5]嘗試消滅「C550-D」中的病毒，",
    "結果\\.・\\.・\\.・",
    "15. [MARKER: Message] 奧斯卡「",
    "反被反噬了……",
    "16. [MARKER: Message] 男子「",
    "\\N[5]的精神被植入了病毒。",
    "17. [MARKER: Message] 男子「",
    "但是，西邊的「埃及」",
    "有一種能潛入人心的魔法——「潛入」術，",
    "我們聽說了這件事。",
    "18. [MARKER: Message] 奧斯卡「",
    "所以你要我們帶個會那種術的人來？",
    "19. [MARKER: Message] 以藏「",
    "你們自己去不就好了……",
    "20. [MARKER: Message] 男子「",
    "新日本的船全都是",
    "電腦控制的……",
    "21. [MARKER: Message] 以藏「",
    "\\S[4]……………真是夠了……",
    "22. [MARKER: Message] 奧斯卡「",
    "沒辦法……只能去了……",
    "23. [MARKER: Message] 以藏「",
    "\\S[3]……好討厭……",
    "24. [MARKER: Message] 奧斯卡「",
    "感染了病毒的「\\N[5]」",
    "派不上用場啊……",
    "25. [MARKER: Message] 以藏「",
    "\\S[3]…………………………",
    "26. [MARKER: Message] 男子「",
    "拜託你們了。",
    "27. [MARKER: Message] 奧斯卡「",
    "但白幫可不行！！",
    "給我們點什麼！！！",
    "28. [MARKER: Message] 男子「",
    "……那……給你們這個……",
    "不知道能不能用……",
    "29. [MARKER: Message] ",
    "　　　　　　　　　　獲得了IC！！",
    "30. [MARKER: Message] 奧斯卡「",
    "我不清楚埃及的具體位置……",
    "31. [MARKER: Message] 男子「",
    "這個嘛……",
    "32. [MARKER: Message] 男子「",
    "拜託你們了。",
    "33. [MARKER: Message] 男子「",
    "\\S[2]哦哦哦哦——！！！",
    "那麼，馬上請這邊——！！！",
])

# Map0029 (中國城鎮)
write_translated("Map0029.txt.trans.txt", [
    "1. [MARKER: Message] 女子「",
    "可享用中華料理的旅館",
    "就是這裡。",
    "2. [MARKER: Message] 女子「",
    "歡迎來到世界最多人口的國家「中國」。",
    "3. [MARKER: Message] 中國人「",
    "哇，這個國家土地雖廣，",
    "地價也便宜……",
    "可偏偏物價高，家具根本買不起。",
    "4. [MARKER: Message] 男子「",
    "嗯？從別國來的人，真少見啊。",
    "5. [MARKER: Message] 大叔「",
    "沿著這條主街往北走，",
    "就是中國天安門。",
    "皇帝陛下就在那裡……",
    "6. [MARKER: Message] 男子「",
    "那邊就是「紫禁城天安門」！！",
    "可惜我們一般人見不到陛下……",
    "7. [MARKER: Message] 男子「",
    "但是，傳說另有一條路，",
    "只要突破大迷宮，",
    "就能直接見到陛下……",
    "8. [MARKER: Message] 男子「",
    "反正……對我們來說是不可能的啦……",
    "9. [MARKER: Message] 老爺爺「",
    "比起西邊的同是亞洲諸國，",
    "我國的發展要先進數倍……",
    "我國是亞洲最大的國家！！！",
    "10. [MARKER: Message] 老爺爺「",
    "水路也都整備得很完善……",
    "這都是年輕皇帝陛下的功勞。",
    "感謝天恩啊……",
    "11. [MARKER: Message] 老爺爺「",
    "這裡是中國拳法的道場。",
    "12. [MARKER: Message] 師傅「",
    "中國拳法天下無敵！！",
    "13. [MARKER: Message] 師傅「",
    "……但是沒有人來……",
    "為……為什麼……",
    "14. [MARKER: Message] 大叔「",
    "哎呀，真是悠閒啊！！",
    "哈哈哈哈！！",
    "15. [MARKER: Message] 奧斯卡「",
    "在這裡問問皇帝",
    "有沒有前往新日本的辦法吧。",
    "16. [MARKER: Message] 以藏「",
    "能突然去找皇帝嗎？",
    "17. [MARKER: Message] 奧斯卡「",
    "不行的話，就強行突破。",
    "18. [MARKER: Message] 以藏「",
    "\\S[2]……",
    "19. [MARKER: Message] 男子「",
    "住在這個住宅區的人，",
    "要麼是出去工作就再也沒回來的，",
    "要麼就是什麼都不做只是混日子的——就這兩種。",
    "20. [MARKER: Message] 男子「",
    "當然，我自己也是那個",
    "混日子那一種啦……",
])

print("Map0027-0029 done.")
