# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0030~0035"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0030 (上鎖的門)
write_translated("Map0030.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　　　　　　上鎖了。",
    "　　　　看樣子是從內側開啟的結構。",
    "2. [MARKER: Message] ",
    "　　　　　　　　上鎖了。",
    "　　　　看樣子是從內側開啟的結構。",
])

# Map0031 (蘇聯邊境 - 入侵)
write_translated("Map0031.txt.trans.txt", [
    "1. [MARKER: Message] 士兵「",
    "此處為蘇維埃社會主義共和國聯邦。",
    "禁止他國人士入境。",
    "請離開。",
    "2. [MARKER: Message] 士兵「",
    "何人！？",
    "3. [MARKER: Message] 以藏「",
    "那個……我迷路了……",
    "可以讓我休息一下嗎……",
    "4. [MARKER: Message] 士兵「",
    "你們不是這個國家的人吧。",
    "遺憾，無法讓你們入境。",
    "5. [MARKER: Message] 以藏「",
    "可惡……",
    "6. [MARKER: Message] 喬喬莉娜「",
    "喂……",
    "7. [MARKER: Message] 士兵「",
    "請離開……",
    "8. [MARKER: Message] 士兵「",
    "此處為蘇維埃社會主義共和國聯邦。",
    "禁止他國人士入境。",
    "請離開。",
    "9. [MARKER: Message] 以藏「",
    "這個看起來可以拆下來。",
    "10. [MARKER: Message] 奧斯卡「",
    "你還真是孩子氣……",
    "11. [MARKER: Message] 以藏「",
    "哼……那算了。\\.",
    "我不拆了……",
    "12. [MARKER: Message] 以藏「",
    "這個，好像可以拆下來耶。",
    "13. [MARKER: Message] ",
    "　　　　　　　　　要試著拆下來嗎？",
    "14. [MARKER: Message] 以藏「",
    "哼——！！！",
    "15. [MARKER: Message] 以藏「",
    "發現梯子！！",
    "16. [MARKER: Message] 喬喬莉娜「",
    "還不錯嘛$g",
    "17. [MARKER: Message] 以藏「",
    "……說得好像老大一樣……",
    "18. [MARKER: Message] 以藏「",
    "這是什麼……？",
    "19. [MARKER: Message] 喬喬莉娜「",
    "說到這裡，這個國家有號稱媲美英國核彈的",
    "超級無敵巨大戰艦……$g",
    "20. [MARKER: Message] 喬喬莉娜「",
    "這樣就回去太不甘心了，",
    "就把它搶過來吧！$g",
    "21. [MARKER: Message] 以藏「",
    "確實……無論如何要從這裡回去，",
    "只有修理這裡的大人物，或者搶走那艘戰艦",
    "別無他法……",
    "22. [MARKER: Message] 喬喬莉娜「",
    "所以嘛，用我的魔法",
    "把這個國家……",
    "23. [MARKER: Message] 以藏「",
    "你打算搞到那個程度！？",
    "24. [MARKER: Message] 以藏「",
    "但是……不解決那些士兵，",
    "搶戰艦根本是天方夜譚……",
    "到底要怎麼辦……",
    "25. [MARKER: Message] 喬喬莉娜「",
    "所以才說，不要拐彎抹角，",
    "讓我的魔法來處理不就好了～$g",
    "26. [MARKER: Message] 以藏「",
    "……找找看有沒有其他入侵路線……",
    "27. [MARKER: Message] 喬喬莉娜「",
    "你到底有沒有在聽我說話！！$g$g",
    "28. [MARKER: Message] 以藏「",
    "……原來這裡還通著……",
    "29. [MARKER: Message] 喬喬莉娜「",
    "既然逃出來了，就再挑戰一次！！$g$g",
    "30. [MARKER: Message] 以藏「",
    "就算再來一次，正面突破也不可能。",
    "只能走其他路線了……",
    "31. [MARKER: Message] 喬喬莉娜「",
    "先回到城市裡吧$g",
    "在這種國家入口根本沒辦法$g",
    "32. [MARKER: Message] 以藏「",
    "確實……在城市裡說不定有什麼通道……",
    "33. [MARKER: Message] 喬喬莉娜「",
    "哪有這種好事$g",
    "34. [MARKER: Message] 以藏「",
    "你真的很討厭……",
])

# Map0032 (澳洲小村)
write_translated("Map0032.txt.trans.txt", [
    "1. [MARKER: Message] 大叔「",
    "天氣真好啊～",
    "2. [MARKER: Message] 神殿騎士「",
    "從這裡可以前往丹迪神殿。",
    "3. [MARKER: Message] 神殿騎士「",
    "路途黑暗，請注意腳下。",
    "4. [MARKER: Message] 女孩「",
    "這裡是澳——洲喔。",
    "雖然是個小村子，請好好休息。",
    "5. [MARKER: Message] 老人「",
    "唔……我年輕的時候也很丹迪……",
    "但老了啊……",
    "6. [MARKER: Message] 老人「",
    "唔……我年輕的時候也很丹迪……",
    "但老了啊……",
    "7. [MARKER: Message] 女子「",
    "我家爺爺啊，最近每天都",
    "這樣眺望著河流……",
    "是老年癡呆了嗎……",
    "8. [MARKER: Message] 戰士「",
    "唔～……要想成為丹迪，",
    "我也得注意一下外表才行……",
    "9. [MARKER: Message] 戰士「",
    "唔～……要想成為丹迪，",
    "我也得注意一下外表才行……",
    "10. [MARKER: Message] 戰士「",
    "唔～……要想成為丹迪，",
    "我也得注意一下外表才行……",
    "11. [MARKER: Message] 大叔「",
    "聽說這個村子裡有通往丹迪神殿的通道……",
    "但到底在哪裡呢？",
])

# Map0033 (丹迪神殿入口 - 阿勝加入)
write_translated("Map0033.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　　　　　\\S[3]請勿觸碰。",
    "2. [MARKER: Message] 奧斯卡「",
    "你一定要去見丹迪之神。",
    "3. [MARKER: Message] 以藏「",
    "雖然很麻煩……但會想辦法的……",
    "4. [MARKER: Message] ",
    "　　　　　　門被反鎖了！！",
    "5. [MARKER: Message] 以藏「",
    "真的再也退不了了……",
    "6. [MARKER: Message] 男子「",
    "要和我比試嗎？",
    "7. [MARKER: Message] 男子「",
    "上——！！！",
    "8. [MARKER: Message] 男子「",
    "……好厲害……",
    "你一定能成為丹迪！！",
    "9. [MARKER: Message] 以藏「",
    "不……不用了……",
    "10. [MARKER: Message] 奧斯卡「",
    "我是女人！！",
    "11. [MARKER: Message] 男子「",
    "還差得遠呢！這樣可成不了丹迪！",
    "12. [MARKER: Message] 以藏「",
    "不……不成也無所謂……",
    "13. [MARKER: Message] 奧斯卡「",
    "我是女人，所以無所謂……",
    "14. [MARKER: Message] 男子「",
    "遺憾……",
    "15. [MARKER: Message] 老爺爺「",
    "丹迪之神就在這裡……",
    "感恩啊，感恩……",
    "16. [MARKER: Message] 老奶奶「",
    "千里迢迢來這裡，果然沒白費……",
    "17. [MARKER: Message] 以藏「",
    "連奶奶也要成為丹迪！？",
    "18. [MARKER: Message] 神殿騎士「",
    "……此處禁止入內……",
    "請離開……",
    "19. [MARKER: Message] 以藏「",
    "我想見見丹迪之神……",
    "讓我見見他……",
    "20. [MARKER: Message] 神殿騎士「",
    "\\S[5]……………………",
    "\\S[2]……好吧……",
    "21. [MARKER: Message] 神殿騎士「",
    "但是，要見那位大人，必須接受丹迪試練……",
    "22. [MARKER: Message] 神殿騎士「",
    "而且，女性無法接受試練……",
    "也就是說，只有你一人必須接受試練。",
    "23. [MARKER: Message] 神殿騎士「",
    "這樣也可以嗎……？",
    "24. [MARKER: Message] 神殿騎士「",
    "那麼，進入這扇門吧……",
    "25. [MARKER: Message] 神殿騎士「",
    "忘了說，接受試練後，",
    "完成之前無法離開……",
    "請做好心理準備。",
    "26. [MARKER: Message] 神殿騎士「",
    "\\S[2]雖然是古老的說法……",
    "\\S[3]Ｇｏｏｄ　Ｌｕｃｋ……",
    "27. [MARKER: Message] 神殿騎士「",
    "……那麼，請離開……",
    "28. [MARKER: Message] 神殿騎士「",
    "\\S[2]雖然是古老的說法……",
    "\\S[3]Ｇｏｏｄ　Ｌｕｃｋ……",
    "29. [MARKER: Message] 神殿騎士「",
    "\\S[2]DANDY大人……？",
    "30. [MARKER: Message] 神殿騎士「",
    "最近，世界的動向有些異常……\\.",
    "DANDY大人也請多加小心。",
    "31. [MARKER: Message] 安德烈「",
    "丹迪……真是個好詞……\\S[5]",
    "（迷醉中……）",
    "32. [MARKER: Message] 神殿騎士「",
    "歡迎蒞臨丹迪神殿……",
    "33. [MARKER: Message] 女子「",
    "這是象徵丹迪之神的雕像。",
    "34. [MARKER: Message] 大叔「",
    "不管什麼時候看，都莊嚴神聖啊……",
    "35. [MARKER: Message] 男子「",
    "我為了能有女朋友，特地來拜見丹迪之神。",
    "像我這樣的人，也能成為丹迪嗎……？",
])

# Map0034 (神殿試練之間)
write_translated("Map0034.txt.trans.txt", [
    "1. [MARKER: Message] 神殿騎士「",
    "此處為「力量之間」。",
    "2. [MARKER: Message] 神殿騎士「",
    "此處為「速度之間」。",
    "3. [MARKER: Message] 神殿騎士「",
    "此處為「智慧之間」。",
    "4. [MARKER: Message] 安德烈「",
    "我……在這裡待著沒問題嗎……",
])

# Map0035 (阿勝加入 & DANDY)
write_translated("Map0035.txt.trans.txt", [
    "1. [MARKER: Message] 奧斯卡「",
    "昏迷了……",
    "是艾倫幹的嗎……",
    "2. [MARKER: Message] 奧斯卡「",
    "居然搞到這個地步……真是大膽……",
    "3. [MARKER: Message] 奧斯卡「",
    "直接走正門太危險了……",
    "算了……",
    "4. [MARKER: Message] 奧斯卡「",
    "直接走正門太危險了……",
    "算了……",
    "5. [MARKER: Message] 奧斯卡「",
    "直接走正門太危險了……",
    "算了……",
    "6. [MARKER: Message] 神殿騎士阿勝「",
    "DANDY大人！！",
    "7. [MARKER: Message] DANDY「",
    "哦，阿勝，你怎麼來了！！",
    "來到這種地方！！",
    "8. [MARKER: Message] 神殿騎士阿勝「",
    "丹迪神殿被某人破壞了！！",
    "9. [MARKER: Message] DANDY「",
    "……什麼——！！！？",
    "10. [MARKER: Message] 神殿騎士阿勝「",
    "我也完全搞不清楚狀況……",
    "11. [MARKER: Message] 神殿騎士阿勝「",
    "……總之！！",
    "請先回去！！",
    "12. [MARKER: Message] DANDY「",
    "\\S[3]……\\S[2]不行……",
    "13. [MARKER: Message] 神殿騎士阿勝「",
    "為什麼！！？",
    "14. [MARKER: Message] DANDY「",
    "我現在有必須做的事……",
    "15. [MARKER: Message] 神殿騎士阿勝「",
    "\\S[2]…………………………",
    "16. [MARKER: Message] 神殿騎士阿勝「",
    "……明白了……",
    "既然您這麼說，",
    "那一定是很重要的事。",
    "17. [MARKER: Message] 神殿騎士阿勝「",
    "但是，事情結束之後請回來喔。",
    "18. [MARKER: Message] DANDY「",
    "我知道了……",
    "……阿勝，既然你都特地來了，",
    "就幫我一把吧。",
    "19. [MARKER: Message] 神殿騎士阿勝「",
    "……明白了。",
    "為了能早日回去，我會盡力協助。",
    "20. [MARKER: Message] ",
    "　　　　神殿騎士阿勝加入了！",
    "21. [MARKER: Message] 奧斯卡「",
    "……對了，你是怎麼知道",
    "DANDY在哪裡的？",
    "22. [MARKER: Message] 神殿騎士阿勝「",
    "那當然，我感應到了DANDY大人的電波……",
    "23. [MARKER: Message] 喬喬莉娜「",
    "啊～～$g　DANDY大人是我的！！$g$g",
    "24. [MARKER: Message] 奧斯卡「",
    "真受歡迎啊。",
    "25. [MARKER: Message] DANDY「",
    "因為我很丹迪嘛。",
])

print("Map0030-0035 done.")
