# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0036 (瑪麗研究室大決戰), Map0037 (巴士底迷宮), Map0038 (巴士底監獄), Map0039 (新日本城市)"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0036 (瑪麗研究室 - 流漸覺醒/JOKER冰封)
write_translated("Map0036.txt.trans.txt", [
    "1. [MARKER: Message] 瑪麗・安托瓦内特「",
    "呵呵……來了嗎……",
    "愚蠢的傢伙們……",
    "2. [MARKER: Message] 瑪麗・安托瓦内特「",
    "\\S[2]拿破崙已跟我說了。",
    "\\S[1]但可惜了！！",
    "研究已經完成！！！",
    "3. [MARKER: Message] 奧斯卡「",
    "\\S[3]什麼？",
    "4. [MARKER: Message] 瑪麗・安托瓦内特「",
    "裝傻也沒用……",
    "你們就站在那裡，",
    "欣賞研究成果吧！！",
    "5. [MARKER: Message] DANDY「",
    "\\S[3]唔！！！",
    "\\S[2]身體……動不了……！！",
    "6. [MARKER: Message] 研究者「",
    "……！！！",
    "7. [MARKER: Message] 阿德蘭斯博士「",
    "完成了……！",
    "8. [MARKER: Message] 瑪麗・安托瓦内特「",
    "是嗎！！！",
    "\\. 那……結果如何？",
    "9. [MARKER: Message] 阿德蘭斯博士「",
    "已解析了流漸的細胞及DNA。",
    "10. [MARKER: Message] 阿德蘭斯博士「",
    "驚人的數值……",
    "這樣的話，長生不死也不是夢！！",
    "11. [MARKER: Message] 阿德蘭斯博士「",
    "每個細胞的能量轉換效率",
    "\\S[2]９９８７２３％\\S[3]……",
    "\\S[2]也就是說，\\S[1]吃一根竹輪可以活１５０年。",
    "12. [MARKER: Message] 阿德蘭斯博士「",
    "為此所需的DNA變換病毒",
    "已製作完成。",
    "13. [MARKER: Message] 瑪麗・安托瓦内特「",
    "\\S[2]呵呵呵呵呵……成功了！！！",
    "\\S[1]我終於美麗永恆，",
    "長生不老！！！！",
    "14. [MARKER: Message] 瑪麗・安托瓦内特「",
    "\\S[2]……等等……\\S[1]那不是喬喬莉娜嗎。",
    "15. [MARKER: Message] 喬喬莉娜「",
    "哎呀，\\. 媽媽$g",
    "16. [MARKER: Message] 所有其他人「",
    "什什什什什什什什什什什什什什什什什什什什什什什",
    "什什什什什什什什什什什什什什什什什什什什什什什",
    "什什什麼——！！！！！？",
    "17. [MARKER: Message] 喬喬莉娜「",
    "你還頑強地活著呢$g",
    "18. [MARKER: Message] 瑪麗・安托瓦内特「",
    "我明明把妳扔進了火山，",
    "為什麼沒死！？",
    "19. [MARKER: Message] 喬喬莉娜「",
    "在把媽媽你轟成碎片之前，我不能死$g",
    "20. [MARKER: Message] 瑪麗・安托瓦内特「",
    "\\S[2]呵呵……",
    "\\S[1]果然還是那個死死活活的孩子呢♪",
    "這次要把脖子砍得乾乾淨淨！",
    "21. [MARKER: Message] 喬喬莉娜「",
    "嘿嘿$g",
    "媽媽你也讓我把你燒成灰燼$g",
    "22. [MARKER: Message] 阿德蘭斯博士「",
    "啊，\\.\\S[3]那個……",
    "23. [MARKER: Message] ？？？「",
    "\\S[2]那個病毒……\\S[1]搶走了！！！！！！",
    "24. [MARKER: Message] 阿德蘭斯博士「",
    "什——麼！！！？",
    "25. [MARKER: Message] 艾倫「",
    "那麼，貝爾、薩斯克，後面就靠你們了！！",
    "26. [MARKER: Message] 薩斯克「",
    "交給我……",
    "27. [MARKER: Message] 瑪麗・安托瓦内特「",
    "你……幹什麼！！？",
    "28. [MARKER: Message] 貝爾「",
    "你們快逃！！！",
    "29. [MARKER: Message] 拿破崙「",
    "\\S[2]……已經來不及了……",
    "30. [MARKER: Message] 貝爾「",
    "你是誰！？在哪裡！！！？",
    "31. [MARKER: Message] 拿破崙「",
    "沒必要回答……",
    "因為你們在這裡就要死了……",
    "32. [MARKER: Message] 拿破崙「",
    "\\S[3]就像羅賽塔一樣……",
    "33. [MARKER: Message] 貝爾「",
    "\\>……！！！\\<",
    "你……羅賽塔……！！？",
    "\\S[2]……可惡……絕不原諒！！",
    "34. [MARKER: Message] 拿破崙「",
    "不原諒又能怎樣！！",
    "35. [MARKER: Message] 貝爾「",
    "嗚——！！！？",
    "36. [MARKER: Message] 薩斯克「",
    "貝爾！！！！？",
    "37. [MARKER: Message] 拿破崙「",
    "……後續就交給你們了……",
    "38. [MARKER: Message] JOKER「",
    "可惡！！我也動不了！！！",
    "39. [MARKER: Message] 奧斯卡「",
    "\\S[2]…………………………",
    "40. [MARKER: Message] 阿勝「",
    "\\S[2]…………………………",
    "41. [MARKER: Message] 瑪麗＝安托瓦內特「",
    "\\S[2]…………………………",
    "42. [MARKER: Message] 薩斯克「",
    "\\S[2]…………………………",
    "43. [MARKER: Message] 薩斯克「",
    "\\S[2]……嗚……",
    "44. [MARKER: Message] 薩斯克「",
    "\\S[2]……嗚嗚嗚嗚嗚嗚……",
    "45. [MARKER: Message] 薩斯克「",
    "\\S[2]……嗚哦哦哦哦哦哦哦——",
    "46. [MARKER: Message] 薩斯克「",
    "……嗚哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦——",
    "——————————————————————",
    "哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦！！",
    "47. [MARKER: Message] 薩斯克「",
    "哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦哦",
    "哦哦哦哦哦哦哦哦哦哦！！！",
    "\\C[5]吼——！！！　斬鐵劍——！！！！！！！！",
    "48. [MARKER: Message] JOKER「",
    "什麼！！？術被破了！！！",
    "不可能！！！！",
    "49. [MARKER: Message] 流漸「",
    "\\S[2]……出……出來了……",
    "50. [MARKER: Message] JOKER「",
    "\\S[2]遵命……",
    "51. [MARKER: Message] 流漸「",
    "哦哦哦哦哦——！！",
    "放我出去——！！！！",
    "52. [MARKER: Message] JOKER「",
    "\\>……！！？\\<",
    "不可能！！流漸覺醒了……！！？",
    "\\>時空封印！！？\\<",
    "53. [MARKER: Message] 流漸「",
    "\\S[2]哦哦哦哦哦哦哦哦哦哦哦——！！！！！",
    "54. [MARKER: Message] JOKER「",
    "這傢伙！！",
    "三次元要崩壞了！！！！！",
    "……不得已了！！",
    "55. [MARKER: Message] JOKER「",
    "\\S[3]時間的霸主，地獄第八層的皇子！",
    "斬斷束縛大地與天空星辰的鎖鏈……",
    "\\S[1]按我的意志，令萬物冰封沉眠！",
    "56. [MARKER: Message] 喬喬莉娜「",
    "哇！！？",
    "那個術——！！！？$g",
    "57. [MARKER: Message] 喬喬莉娜「",
    "快逃！！！$g",
    "蟲洞！！！$g$g",
    "58. [MARKER: Message] 奧斯卡「",
    "\\S[3]……\\S[2]這樣不太對吧……",
    "59. [MARKER: Message] 神殿騎士阿勝「",
    "\\S[2]……同感……",
    "60. [MARKER: Message] 薩斯克「",
    "太殘忍了……",
    "61. [MARKER: Message] JOKER「",
    "\\S[2]哈哈哈！！ \\>流漸！！\\<",
    "\\S[1]你就老老實實待在那裡！！",
    "\\|\\S[3]冰・縛・結・界！！！！！！",
    "62. [MARKER: Message] 瑪麗・安托瓦内特「",
    "你連我也要冰凍！！？",
    "63. [MARKER: Message] JOKER「",
    "\\S[2]呵呵呵……",
    "沉睡吧……！！ \\S[3]永遠地……",
    "64. [MARKER: Message] 喬喬莉娜「",
    "唷，得救了$g",
    "65. [MARKER: Message] 喬喬莉娜「",
    "咦？$g　DANDY大人——？$g$g",
    "66. [MARKER: Message] 喬喬莉娜「",
    "要去找他！！$g$g",
])

# Map0037 (巴士底監獄迷宮走廊)
write_translated("Map0037.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　　　門緊緊地關著……",
    "2. [MARKER: Message] 奧斯卡「",
    "應該在某處有能打開這扇門的控制桿。",
    "找找看吧。",
    "3. [MARKER: Message] ",
    "　　　　　聽到了某處解鎖的聲音。",
    "4. [MARKER: Message] DANDY「",
    "這是什麼構造？",
    "5. [MARKER: Message] 奧斯卡「",
    "……不清楚……",
    "6. [MARKER: Message] ",
    "　　　　　　　　聽到了上鎖的聲音。",
    "7. [MARKER: Message] 奧斯卡「",
    "關上它幹嘛……",
    "8. [MARKER: Message] 丹迪「",
    "哎呀……",
    "9. [MARKER: Message] 士兵「",
    "這裡為了防範逃獄，特意設計得非常複雜。",
    "簡直就是個迷宮呢。",
    "10. [MARKER: Message] 士兵「",
    "其實我也不例外，",
    "迷路了……",
    "真是丟臉呢。",
    "11. [MARKER: Message] DANDY「",
    "真是的呢。",
])

# Map0038 (巴士底監獄牢房)
write_translated("Map0038.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　　　　　　士兵已昏迷。",
    "2. [MARKER: Message] ",
    "　　　　　　　　士兵已昏迷。",
    "3. [MARKER: Message] 老爺爺「",
    "我能活著出去嗎……",
    "刑期一百二十年……",
    "4. [MARKER: Message] 男子「",
    "哦——！！",
    "摸一下女戰士的皮膚有什麼不對嗎——！！",
    "5. [MARKER: Message] 奧斯卡「",
    "這是非常嚴重的性騷擾。",
    "6. [MARKER: Message] 士兵「",
    "你們是什麼人……！",
    "7. [MARKER: Message] 士兵「",
    "可惡……",
    "8. [MARKER: Message] 奧斯卡「",
    "看！",
    "9. [MARKER: Message] 奧斯卡「",
    "看！",
    "10. [MARKER: Message] 男子「",
    "我到底做了什麼——！？",
    "11. [MARKER: Message] 老奶奶「",
    "呵呵呵……",
    "我看見你們的死相了……",
    "呵呵呵……",
    "12. [MARKER: Message] 大叔「",
    "可惡……沒想到持續了５年的",
    "內褲小偷就這樣被發現了……",
    "13. [MARKER: Message] 男子「",
    "你們是什麼人！？",
    "是來把我處決的嗎……！？",
])

# Map0039 (新日本城市 - 機器人)
write_translated("Map0039.txt.trans.txt", [
    "1. [MARKER: Message] 市民「",
    "好窄。",
    "2. [MARKER: Message] 折扣商店「",
    "歡迎光臨！",
    "3. [MARKER: Message] 折扣商店「",
    "雖然便宜，性能一樣！",
    "4. [MARKER: Message] 男子「",
    "任務完成，暫時停止運作……",
    "5. [MARKER: Message] ",
    "　　功能停止中，一動也不動。",
    "6. [MARKER: Message] 安德烈「",
    "這裡是藥店。",
])

print("Map0036-0039 done.")
