# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0040~0047"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0040 (新生新日本號船艙內部)
write_translated("Map0040.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "……？\\. 咦？",
    "傳送裝置不見了……",
    "2. [MARKER: Message] 奧斯卡「",
    "……真的耶……",
    "3. [MARKER: Message] 以藏「",
    "這種地方以前有樓梯嗎……？",
    "4. [MARKER: Message] DANDY「",
    "新日本的構造改變了……？",
    "還是說，這是陷阱……？",
    "5. [MARKER: Message] 喬喬莉娜「",
    "去找流漸先生的話，不是比較快嗎$g$g",
    "6. [MARKER: Message] DANDY「",
    "也是呢……",
    "7. [MARKER: Message] 男子「",
    "我要將家傳的傳統招式，",
    "傳授給即將奔赴死地的你們……",
    "8. [MARKER: Message] 以藏「",
    "你這傢伙不是機器人嗎……？",
    "9. [MARKER: Message] 男子「",
    "\\s[5]……………………………………………………。",
    "10. [MARKER: Message] ",
    "　　奧斯卡學會了「日本傳統槍技『雅』」！",
    "11. [MARKER: Message] 以藏「",
    "被敷衍過去了……",
    "12. [MARKER: Message] 男子「",
    "任務完成……功能停止。",
    "13. [MARKER: Message] 以藏「",
    "果然是機器人……",
    "14. [MARKER: Message] ",
    "　　因功能停止，一動也不動。",
    "15. [MARKER: Message] 男子「",
    "這裡已經不再是員工室了。",
    "真遺憾……",
    "16. [MARKER: Message] 男子「",
    "不過在此之前，我真的有做過",
    "像是員工該做的事嗎……",
    "17. [MARKER: Message] 男子「",
    "在突入美國時，我到甲板上看了一下，",
    "在防衛線南邊，能看到一座村莊喔。\\.",
    "去一次看看如何？",
    "18. [MARKER: Message] 男子「",
    "啊，不過那裡被群山環繞，",
    "看來只能用這個去，或者搭乘飛空艇去呢……",
    "19. [MARKER: Message] 男子「",
    "終於要前往敵方的大本營了呢……。\\.",
    "啊啊……\\. 我明明什麼都做不到，卻渾身發抖……",
    "20. [MARKER: Message] 男子「",
    "啊……\\. 那邊的機器似乎還活著，\\. ",
    "所以看來還是可以記錄的。",
    "21. [MARKER: Message] ＞要記錄目前的狀態嗎？",
    "22. [MARKER: Message] 機工士「",
    "沒想到居然有這麼厲害的船！！",
    "23. [MARKER: Message] 女僕「",
    "我正在打掃新生新日本號。",
    "真想穿穿看女僕裝啊～",
    "24. [MARKER: Message] 奧斯卡「",
    "喔喔！女僕！",
    "25. [MARKER: Message] 女僕「",
    "奧斯卡大人！",
    "我也會作為情報收集員一起戰鬥的！",
    "26. [MARKER: Message] 若者「",
    "我也要戰鬥！\\. ",
    "\\s[2]……………………",
    "……………………肚子有點……",
    "27. [MARKER: Message] 安德烈粉絲的女子「",
    "這間房間是安德烈大人的房間喔$g",
    "王座看起來超酷的～",
    "28. [MARKER: Message] 薩斯克「",
    "好窄啊。",
    "29. [MARKER: Message] 貝爾「",
    "香菸抽完了……",
    "30. [MARKER: Message] 戰「",
    "就讓你們看看，",
    "中國拳法的威力！",
    "31. [MARKER: Message] 鳥「",
    "咕？",
    "32. [MARKER: Message] 拉ルフ「",
    "這次輪到我來幫忙了！",
    "33. [MARKER: Message] 阿勝「",
    "DANDY大人！",
    "我也要一起戰鬥！",
    "34. [MARKER: Message] DANDY「",
    "喔喔！阿勝！",
    "要注意身體，好好加油！",
    "35. [MARKER: Message] 阿勝「",
    "是！！！！！！！！！！！！！！",
    "36. [MARKER: Message] 機器人「",
    "要休息一下嗎？",
    "37. [MARKER: Message] 熱血女「",
    "熱血沸騰！",
    "根本坐不住！",
    "你也是這樣吧！",
    "38. [MARKER: Message] 熱血女「",
    "沒錯吧沒錯吧！",
    "我覺得和你很合得來！",
    "這個送給你！",
    "39. [MARKER: Message] ",
    "　　　　獲得了裂爪 Soul of Dandizm！",
    "40. [MARKER: Message] 熱血女「",
    "切…………",
    "我最討厭冷淡的傢伙了！",
    "41. [MARKER: Message] 熱血女「",
    "熱血最棒！",
    "42. [MARKER: Message] 武器店「",
    "我的武器是最強的！",
    "43. [MARKER: Message] 防具店「",
    "我們家的防具是最棒的唷！",
    "44. [MARKER: Message] 道具店「",
    "什麼東西都有喔！",
])

# Map0041 (上鎖的門)
write_translated("Map0041.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　　　　門上鎖了……",
])

# Map0042 (印度民家與機工士)
write_translated("Map0042.txt.trans.txt", [
    "1. [MARKER: Message] 老爺爺「",
    "啊，真好喝。",
    "水可是世界的珍寶啊。",
    "2. [MARKER: Message] 大叔「",
    "你說新日本啊……",
    "3. [MARKER: Message] 大叔「",
    "比起這裡，我覺得去北邊的印度市區",
    "更能收集到情報喔。",
    "4. [MARKER: Message] 老奶奶「",
    "……………………。",
    "5. [MARKER: Message] 老奶奶「",
    "最近世界的局勢很奇怪……",
    "希望這裡不要受到波及就好……",
    "6. [MARKER: Message] 以藏「",
    "\\S[5]啊啊……\\S[3]累死了……",
    "7. [MARKER: Message] 奧斯卡「",
    "……有沒有人知道，",
    "關於前往新日本的情報呢……",
    "8. [MARKER: Message] 以藏「",
    "打聽情報嗎……真麻煩啊～……",
    "9. [MARKER: Message] 機工士「",
    "喔……那，要好好珍惜使用啊！",
    "10. [MARKER: Message] ",
    "　　　　　　獲得了柯爾特巨蟒！！",
    "11. [MARKER: Message] 機工士「",
    "雖然有IC，但看來好像沒有電晶體呢。",
    "12. [MARKER: Message] 機工士「",
    "喔……那，要好好珍惜使用啊！",
    "13. [MARKER: Message] ",
    "　　　　　　獲得了柯爾特巨蟒！！",
    "14. [MARKER: Message] 機工士「",
    "雖然有電晶體，但看來好像沒有IC呢。",
    "15. [MARKER: Message] 機工士「",
    "如果你把IC和電晶體拿給我的話，",
    "我就幫你做一把「柯爾特巨蟒」喔。",
    "16. [MARKER: Message] 機工士「",
    "我？\\S[2]……我是個流浪的機工士……",
    "17. [MARKER: Message] 機工士「",
    "以後要是又拿到什麼奇怪的零件，",
    "就帶過來給我吧。",
    "18. [MARKER: Message] 機工士「",
    "我會根據不同的零件來幫你製作道具的。",
    "19. [MARKER: Message] 商人「",
    "聽說東邊「中國」的皇帝，",
    "花了大筆稅金，建造了像這艘船一樣的",
    "大型船隻呢。",
    "20. [MARKER: Message] 商人「",
    "那皇帝肯定只是在花錢享樂吧～……",
])

# Map0043 (中國巨船港口)
write_translated("Map0043.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　　　　中華人民共和國，萬歲",
    "2. [MARKER: Message] 兵士「",
    "你是政府的人嗎？",
    "3. [MARKER: Message] 兵士「",
    "\\S[2]………………。",
    "\\S[1]看來不是呢。",
    "4. [MARKER: Message] 兵士「",
    "這裡的船隻，全都是中國皇帝的財產。",
    "沒有皇帝的許可，請不要再往前走。",
    "5. [MARKER: Message] 兵士「",
    "你是政府的人嗎？",
    "6. [MARKER: Message] 兵士「",
    "\\S[2]………………。",
    "\\S[1]看來不是呢。",
    "7. [MARKER: Message] 兵士「",
    "這裡的船隻，全都是中國皇帝的財產。",
    "沒有皇帝的許可，請不要再往前走。",
    "8. [MARKER: Message] 奧斯卡「",
    "許可的話我拿到了。\|",
    "你看。",
    "9. [MARKER: Message] 兵士「",
    "\\S[3]那……那是皇帝的墜飾！！",
    "10. [MARKER: Message] 兵士「",
    "……我明白了。",
    "請盡管使用吧。",
    "11. [MARKER: Message] 兵士「",
    "其實，皇帝自己一次都沒用過",
    "這艘船。",
    "12. [MARKER: Message] 兵士「",
    "讓你們這樣的人來使用，",
    "對這艘船來說也是得償所願吧。",
    "13. [MARKER: Message] 兵士「",
    "啊……！我也要回去了！！",
    "14. [MARKER: Message] 以藏「",
    "\\S[3]………………………………。",
    "15. [MARKER: Message] 奧斯卡「",
    "\\S[3]………………………………。",
    "16. [MARKER: Message] 兵士「",
    "啊——，從國家派來的士兵",
    "什麼時候才能來跟我交接啊……",
    "17. [MARKER: Message] 兵士「",
    "不，應該說，既然看守船隻的工作都沒了，",
    "為什麼我們還得在這裡",
    "繼續看守呢……",
    "18. [MARKER: Message] 以藏「",
    "……那直接回去不就好了……",
    "19. [MARKER: Message] 喬喬莉娜「",
    "直接回去就好了嘛$g",
    "20. [MARKER: Message] 兵士「",
    "………………說的也是……",
    "回去吧！！！",
])

# Map0045 (中國巨船內部通道)
write_translated("Map0045.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "……打不開啊……這扇門……",
    "2. [MARKER: Message] 奧斯卡「",
    "打不開的話，就是上鎖了吧。",
    "鑰匙一定在某個地方。",
    "3. [MARKER: Message] 以藏「",
    "既然不能馬上打開，",
    "那不打開也無所謂吧……",
    "4. [MARKER: Message] 奧斯卡「",
    "像這種防衛嚴密的門後面，",
    "一定有什麼重要的東西！",
    "5. [MARKER: Message] 以藏「",
    "而且仔細看的話，根本沒有鑰匙孔啊……",
    "6. [MARKER: Message] 奧斯卡 "
    "\\S[2]……真的耶……",
    "\\S[1]難道是用別的方法打開的嗎……？",
    "7. [MARKER: Message] 以藏「",
    "\\>咦？\\<\\. 門的右邊有東西耶。",
    "8. [MARKER: Message] 以藏「",
    "原來如此，要把卡片插進這扇門",
    "旁邊的這個地方啊……",
    "9. [MARKER: Message] 奧斯卡「",
    "這只是把鑰匙孔的位置改了一下而已呢。",
    "10. [MARKER: Message] 奧斯卡「",
    "看來是打開了。",
    "走吧，我們進去。",
    "11. [MARKER: Message] ",
    "　　　從這一側打不開。",
    "　看來是從相反側被鎖住了。",
    "12. [MARKER: Message] ",
    "　　　有個可以插入東西的槽。",
    "　從形狀來看，似乎可以插入卡片大小的東西。",
    "13. [MARKER: Message] 以藏「",
    "原來如此，要把卡片插進這扇門",
    "旁邊的這個地方啊……",
    "14. [MARKER: Message] 奧斯卡「",
    "這只是把鑰匙孔的位置改了一下而已呢。",
    "15. [MARKER: Message] 奧斯卡「",
    "看來是打開了。",
    "走吧，我們進去。",
    "16. [MARKER: Message] ",
    "　　　　　　獲得了４０００Ｄ！！",
    "17. [MARKER: Message] ",
    "　　　從這一側打不開。",
    "　看來是從相反側被鎖住了。",
])

# Map0046 (中國巨船內部旋轉地板)
write_translated("Map0046.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "\\S[2]這是什麼……？",
    "\\S[1]旋、\\.旋轉地板……！！？",
    "2. [MARKER: Message] 以藏「",
    "要是運氣不好的話，根本到不了想去的地方嘛……",
    "\\.好煩人……",
    "3. [MARKER: Message] 奧斯卡「",
    "正確的路線在下面嗎……？",
])

# Map0047 (中國巨船內部監獄/兵營)
write_translated("Map0047.txt.trans.txt", [
    "1. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "2. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "3. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "4. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "5. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "6. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "7. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "8. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "9. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "10. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "11. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "12. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "13. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "14. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "15. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "16. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "17. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "18. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "19. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "20. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "21. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "22. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "23. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "24. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "25. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "26. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "27. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "28. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "29. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "30. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "31. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "32. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "33. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！? ",
    "34. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "35. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "36. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "37. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "38. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "39. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "40. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "41. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "42. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "43. [MARKER: Message] 警備兵 "
    "什麼人！你們這群傢伙！！？",
    "44. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "45. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "46. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "47. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "48. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "49. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "50. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "51. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "52. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "53. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "54. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "55. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "56. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "57. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "58. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "59. [MARKER: Message] 安德烈「",
    "以藏！已經沒有鑰匙了喔！",
    "60. [MARKER: Message] 以藏「",
    "也就是說……這一層樓的門都打不開了",
    "是這樣吧……。",
    "61. [MARKER: Message] 奧斯卡「",
    "只能放棄了呢……。",
    "62. [MARKER: Message] ",
    "　　　鑰匙用完之後，請放回櫃子裡",
    "",
    "　　　　　　　　　　　　　　　　　中國兵團委員會",
    "63. [MARKER: Message] 以藏「",
    "……找到鑰匙了喔。",
    "64. [MARKER: Message] 奧斯卡「",
    "看來有４把備用鑰匙，和１把不同的鑰匙。",
    "可能是很久沒被使用了，",
    "鑰匙都破破爛爛的……。",
    "65. [MARKER: Message] 以藏「",
    "也就是說，用一次就會壞掉啊……。",
    "66. [MARKER: Message] ",
    "　 獲得了４把拋棄式鑰匙，和１把入口鑰匙！",
    "67. [MARKER: Message] 以藏「",
    "鑰匙已經拿到了吧。",
    "68. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "69. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "70. [MARKER: Message] 警備兵「",
    "什麼人！你們這群傢伙！！？",
    "71. [MARKER: Message] 警備兵「",
    "咕哇……。",
    "72. [MARKER: Message] 以藏「",
    "有鑰匙也有警備兵……。",
    "這一層樓到底是搞什麼鬼……。",
    "73. [MARKER: Message] 奧斯卡「",
    "這代表著有如此重要的東西沉眠於此嗎……？",
    "74. [MARKER: Message] 以藏「",
    "從這一層漂浮的氣息來看，",
    "警備兵看來不只剛剛那些人而已呢……。",
    "75. [MARKER: Message] 奧斯卡「",
    "而且備用鑰匙有４把……。",
    "如果能好好利用這個，",
    "說不定能避免與警備兵交戰。",
    "76. [MARKER: Message] 以藏「",
    "思考太麻煩了，直接把警備兵打倒",
    "強行突破如何？",
    "鑰匙也不會浪費。",
    "77. [MARKER: Message] 奧斯卡「",
    "\\S[3]……。",
    "\\S[1]好吧……交給你決定……。",
    "78. [MARKER: Message] ",
    "　　　　請巧妙利用４把備用鑰匙，",
    "　　　　　　抵達那個小房間。",
    "79. [MARKER: Message] ",
    "　　　　　　在抵達小房間之前，",
    "　　若４把備用鑰匙用光了，就得重來一次。",
    "80. [MARKER: Message] 奧斯卡「",
    "感覺不到士兵們的氣息……。",
    "81. [MARKER: Message] 以藏「",
    "\\S[3]……\\S[2]難道……",
    "\\S[1]全都被人幹掉了……！？",
    "82. [MARKER: Message] 奧斯卡「",
    "別說這種可怕的話……。",
    "恐怕是知道了我們的行動，",
    "而在皇帝陛下的身邊集結了吧。",
    "83. [MARKER: Message] 以藏「",
    "也就是說……等一下我們得和那一大群士兵",
    "正面交鋒囉……。",
    "84. [MARKER: Message] 奧斯卡「",
    "就是這樣。",
    "85. [MARKER: Message] 以藏「",
    "啊……打不開……！",
    "86. [MARKER: Message] 奧斯卡「",
    "看來……需要鑰匙呢……。",
    "87. [MARKER: Message] 以藏「",
    "那個櫃子……很可疑呢……。",
    "88. [MARKER: Message] 以藏「",
    "這是……？",
    "89. [MARKER: Message] 奧斯卡「",
    "這一層的鳥瞰圖……？",
    "90. [MARKER: Message] 奧斯卡「",
    "呃……。",
    "91. [MARKER: Message] 　　　防範入侵者，請按照上述內容配置兵力。",
    "　　　　　\\C[5]紅\\C[0]為兵力，\\C[4]黃\\C[0]為門，",
    "　　　　　而\\C[9]綠\\C[0]則是必須誓死守護的場所。",
    "92. [MARKER: Message] 奧斯卡「",
    "看來是這樣呢。",
    "也就是說，這一層的中心有著什麼東西吧。",
    "93. [MARKER: Message] 　　　防範入侵者，請按照上述內容配置兵力。",
    "　　　　　\\C[5]紅\\C[0]為兵力，\\C[4]黃\\C[0]為門，",
    "　　　　　而\\C[9]綠\\C[0]則是必須誓死守護的場所。",
    "94. [MARKER: Message] 安德烈「",
    "真……真是大迷宮啊……（吞口水）",
    "95. [MARKER: Message] ",
    "　　　　　從內側鎖上了！",
])

print("Map0040-0047 done.")
