# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0048~0055"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0048 (中國巨船內部 ID卡房間)
write_translated("Map0048.txt.trans.txt", [
    "1. [MARKER: Message] 奧斯卡「",
    "以藏，我們來找找有沒有什麼重要的東西吧。",
    "2. [MARKER: Message] 士兵「",
    "嗯……！！",
    "3. [MARKER: Message] 士兵「",
    "什麼人，你們這群傢伙！！！？",
    "4. [MARKER: Message] 以藏「",
    "我們是來見這裡的皇帝陛下的……",
    "5. [MARKER: Message] 士兵「",
    "\\S[2]皇帝陛下……？",
    "真是可疑的傢伙們……",
    "6. [MARKER: Message] 士兵「",
    "總之，非相關人員",
    "禁止入內！！",
    "快點離開！",
    "7. [MARKER: Message] 奧斯卡「",
    "那可不行。",
    "有那麼嚴密的警備網，",
    "這裡一定有什麼重要的東西吧。",
    "8. [MARKER: Message] 奧斯卡「",
    "總之，先請礙事的人退場吧。",
    "9. [MARKER: Message] 士兵「",
    "嗚哇……。",
    "10. [MARKER: Message] 奧斯卡「",
    "我們稍微調查一下這間房間，",
    "看看有沒有什麼重要的東西吧。",
    "11. [MARKER: Message] 奧斯卡「",
    "來找找看有沒有什麼東西吧……",
    "12. [MARKER: Message] 以藏「",
    "這已經達到小偷的境界了吧……。",
    "13. [MARKER: Message] 奧斯卡「",
    "看來沒有什麼特別重要的東西呢。",
    "14. [MARKER: Message] 奧斯卡「",
    "來找找看有沒有什麼東西吧……",
    "15. [MARKER: Message] 以藏「",
    "這已經達到小偷的境界了吧……。",
    "16. [MARKER: Message] 奧斯卡「",
    "\\S[3]……嗯！？",
    "這是……。",
    "17. [MARKER: Message] ",
    "　　　　　　　　　獲得了ID卡！！",
    "18. [MARKER: Message] 以藏「",
    "看來和機械文明的ID卡不太一樣呢。",
    "像是機關之類的東西？",
    "19. [MARKER: Message] 奧斯卡「",
    "看來是這樣……剩下的就是這要在哪裡使用呢……。",
    "20. [MARKER: Message] 以藏「",
    "\\S[3]……在我們之前走過的地方，",
    "有沒有什麼可疑的場所啊……。",
    "21. [MARKER: Message] 以藏「",
    "看來已經什麼都沒有了呢。",
    "22. [MARKER: Message] ",
    "　　　　　　　士兵似乎昏迷了。",
    "23. [MARKER: Message] 奧斯卡「",
    "以藏，我們來找找有沒有什麼重要的東西吧。",
])

# Map0050 (中國皇宮 - 末代皇帝與約會)
write_translated("Map0050.txt.trans.txt", [
    "1. [MARKER: Message] 末代皇帝「",
    "\\S[3]什麼人，你們是？",
    "2. [MARKER: Message] 奧斯卡「",
    "我們想詢問前往新日本的方法。",
    "3. [MARKER: Message] 末代皇帝「",
    "\\S[3]新日本啊……。",
    "4. [MARKER: Message] 末代皇帝「",
    "\\S[3]很遺憾，要前往新日本，",
    "除了坐船之外，沒有別的辦法了。",
    "5. [MARKER: Message] 奧斯卡「",
    "……那沒有開往新日本的船隻嗎？",
    "6. [MARKER: Message] 末代皇帝「",
    "\\S[3]沒有……不過，把朕的船",
    "讓給你們也是可以的喔。",
    "7. [MARKER: Message] 奧斯卡「",
    "\\>真的嗎！？\\<",
    "非常感謝您～$g",
    "8. [MARKER: Message] 末代皇帝「",
    "\\S[3]但是，朕有一個條件……。",
    "9. [MARKER: Message] 奧斯卡「",
    "是什麼呢？",
    "10. [MARKER: Message] 末代皇帝「",
    "\\S[3]跟朕約會吧！！",
    "11. [MARKER: Message] 末代皇帝「",
    "\\S[3]真的嗎！？",
    "那麼，往夢幻的世界，Let's Go！！",
    "12. [MARKER: Message] ",
    "　　　　　　　　　　獲得了船隻！！！",
    "13. [MARKER: Message] 殘渣「",
    "\\S[2]……………………………………………………",
    "……………………………………………………",
    "……………………………………………………。",
    "14. [MARKER: Message] 以藏「",
    "他剛剛說了什麼？",
    "15. [MARKER: Message] 奧斯卡「",
    "他說船在南邊的停泊處喔。",
    "16. [MARKER: Message] 以藏「",
    "嗯？有東西在發光耶。",
    "17. [MARKER: Message] 奧斯卡「",
    "……這是中國王族的證明……。",
    "18. [MARKER: Message] 奧斯卡「",
    "說不定能成為某種證明。",
    "雖然不太好，但我們就收下吧。",
    "19. [MARKER: Message] 以藏「",
    "這樣真的好嗎～……。",
    "20. [MARKER: Message] ",
    "　　　　　　獲得了王族的墜飾！！",
    "21. [MARKER: Message] 奧斯卡「",
    "走吧。",
    "22. [MARKER: Message] 末代皇帝「",
    "\\S[3]那麼，這件事就當作沒發生過吧。",
    "23. [MARKER: Message] 末代皇帝「",
    "\\S[3]想跟朕約會了嗎？",
    "24. [MARKER: Message] 末代皇帝「",
    "\\S[3]真的嗎！？",
    "那麼，往夢幻的世界，Let's Go！！",
    "25. [MARKER: Message] ",
    "　　　　　　　　　　獲得了船隻！！！",
    "26. [MARKER: Message] 殘渣「",
    "\\S[2]……………………………………………………",
    "……………………………………………………",
    "……………………………………………………。",
    "27. [MARKER: Message] 以藏「",
    "他剛剛說了什麼？",
    "28. [MARKER: Message] 奧斯卡「",
    "他說船在南邊的停泊處喔。",
    "29. [MARKER: Message] 以藏「",
    "嗯？有東西在發光耶。",
    "30. [MARKER: Message] 奧斯卡「",
    "……這是中國王族的證明……。",
    "31. [MARKER: Message] 奧斯卡「",
    "說不定能成為某種證明。",
    "雖然不太好，但我們就收下吧。",
    "32. [MARKER: Message] 以藏「",
    "這樣真的好嗎～……。",
    "33. [MARKER: Message] ",
    "　　　　　　獲得了王族的墜飾！！",
    "34. [MARKER: Message] 奧斯卡「",
    "走吧。",
    "35. [MARKER: Message] 末代皇帝「",
    "\\S[3]那麼，這件事就當作沒發生過吧。",
    "36. [MARKER: Message] 榨乾的殘渣「",
    "\\S[2]……………………………………………………",
    "……………………………………………………",
    "……………………………………………………。",
    "37. [MARKER: Message] 宰相「",
    "聽說在南邊的國家「澳洲」，",
    "有著丹迪之神喔。",
    "38. [MARKER: Message] 宰相「",
    "要不，我也去看看吧。",
    "39. [MARKER: Message] 武成王「",
    "陛下才５歲……。",
    "這個國家也撐不了多久了呢……。",
    "40. [MARKER: Message] 武成王「",
    "要是先代皇帝沒有在遠征中喪命的話，",
    "也不至於會變成這樣……。",
    "\\S[3]……可惡！！",
    "41. [MARKER: Message] 武成王「",
    "這個國家……也完蛋了……。",
])

# Map0052 (打開大門)
write_translated("Map0052.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　　　　　　　打開了正門的大門！",
    "2. [MARKER: Message] ",
    "　　　　　　　　　打開了正門的大門！",
    "3. [MARKER: Message] ",
    "　　　　　　　　　打開了正門的大門！",
])

# Map0053 (印度市區房屋與倉庫)
write_translated("Map0053.txt.trans.txt", [
    "1. [MARKER: Message] 男子「",
    "你知道里德・艾倫嗎？",
    "2. [MARKER: Message] 男子「",
    "那傢伙明明是個怪盜，人卻挺好的呢。",
    "這就叫做「義賊」嗎？",
    "3. [MARKER: Message] 男子「",
    "你居然不知道那個名震天下的大怪盜嗎！？",
    "4. [MARKER: Message] 男子「",
    "那位大怪盜，把錢分給了我們這些貧窮的平民。",
    "這是一生都忘不了的事件啊……。",
    "5. [MARKER: Message] 女子「",
    "真是的，那個人總是天天在聊",
    "里德的事情呢。",
    "6. [MARKER: Message] 女子「",
    "身為女人的我都快要嫉妒了呢……。",
    "7. [MARKER: Message] 大叔「",
    "喂喂，不能進去這裡喔。",
    "8. [MARKER: Message] 大叔「",
    "這裡是存放從港口運來的物資的倉庫。",
    "沒事的人可不能進去喔。",
    "9. [MARKER: Message] 大叔「",
    "話說……你該不會是像里德・艾倫一樣，",
    "打算來偷東西的吧……。",
    "10. [MARKER: Message] ",
    "　　　　　　　　獲得了回復機！！",
    "11. [MARKER: Message] ",
    "　　　　　　　　獲得了散彈槍！！",
    "12. [MARKER: Message] ",
    "　　　　　　　　　　獲得了魔法藥！！",
    "13. [MARKER: Message] 大叔「",
    "你知道澳洲這個國家嗎？",
    "14. [MARKER: Message] 大叔「",
    "聽說那個國家有一座叫做丹迪神殿的神殿呢。",
    "15. [MARKER: Message] 這是仙人掌。",
    "16. [MARKER: Message] 喜歡仙人掌的老爺爺「",
    "仙人掌最喜歡炎熱的氣候了，",
    "我就是為了解這株仙人掌，",
    "才特地搬到印度來的喔。",
    "17. [MARKER: Message] 喜歡仙人掌的老爺爺的孫女「",
    "爺爺對仙人掌的狂熱，真是讓人困擾啊……",
])

# Map0054 (澳洲小村後方路徑)
write_translated("Map0054.txt.trans.txt", [
    "1. [MARKER: Message] 男子「",
    "穿過這裡就是丹迪神殿了！",
    "這樣我也能成為丹迪啦～。",
    "2. [MARKER: Message] 老人「",
    "老夫也要成為丹迪！！",
    "老夫可不會輸給那些年輕小夥子！！",
])

# Map0055 (神殿騎士指示)
write_translated("Map0055.txt.trans.txt", [
    "1. [MARKER: Message] 神殿騎士「",
    "丹迪神殿在西邊。",
    "請路上小心。",
])

print("Map0048-0055 done.")
