# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0067~0073"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0067 (精神世界門口)
write_translated("Map0067.txt.trans.txt", [
    "1. [MARKER: Message] 安德烈「",
    "\\S[3]出……\\S[2]出不去……。",
])

# Map0070 (流漸精神世界1 - 大戰記憶)
write_translated("Map0070.txt.trans.txt", [
    "1. [MARKER: Message] 流漸「",
    "……月……４日……",
    "太空火箭……完成……。",
    "前往宇宙的啟航就在眼前了。",
    "2. [MARKER: Message] 流漸「",
    "２月・８日……第３次……大戰……。",
    "來得及從這顆星球脫逃嗎……？",
    "3. [MARKER: Message] 奧斯卡「",
    "你在說什麼……？",
    "這是怎麼回事……？",
    "4. [MARKER: Message] 流漸「",
    "……核武器……。",
    "難道惡夢又要重演了嗎……！？",
    "5. [MARKER: Message] 以藏「",
    "惡夢重演……？",
    "你是說以前也有過核武器嗎？",
    "6. [MARKER: Message] 流漸「",
    "………………！！？",
    "\\.唔\\.……、\\.哇啊\\.……！",
    "7. [MARKER: Message] 以藏「",
    "……剛才那是……？",
    "他到底發生了什麼事……？",
    "8. [MARKER: Message] DANDY「",
    "……唔……！",
    "9. [MARKER: Message] 喬喬莉娜「",
    "DANDY大人～～～！！$g$g",
    "10. [MARKER: Message] 以藏「",
    "……這……這裡是……？",
    "11. [MARKER: Message] 奧斯卡「",
    "我們從精神世界回來了嗎……？",
    "12. [MARKER: Message] 以藏「",
    "……不過，感覺不太對勁呢。",
    "這裡到底是哪裡啊？這是……？",
    "13. [MARKER: Message] DANDY「",
    "的確……這不是我們所熟知的地方呢……。",
    "14. [MARKER: Message] 喬喬莉娜「",
    "……真奇怪呢。照理來說，從精神潛入的空間裡",
    "突然被傳送到其他地方，",
    "是絕對不可能發生的事情啊$g",
    "15. [MARKER: Message] 以藏「",
    "如果這裡還是在精神世界的話，流漸應該",
    "在某個地方才對吧……。",
    "16. [MARKER: Message] 奧斯卡「",
    "與其在這裡空想，不如去找找看吧……。",
    "總之，先行動吧。",
])

# Map0072 (流漸精神世界2 - 遭遇病毒)
write_translated("Map0072.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "流漸，你所描繪的這副景象",
    "到底是……。",
    "2. [MARKER: Message] 流漸「",
    "……已經……。",
    "這裡完蛋了……。",
    "3. [MARKER: Message] 流漸「",
    "這顆星球……早就死絕了……。",
    "4. [MARKER: Message] 奧斯卡「",
    "你到底是……何方神聖……！？",
    "星球死絕了……這到底是怎麼一回事？",
    "5. [MARKER: Message] 流漸「",
    "…………………………………………。",
    "6. [MARKER: Message] 以藏「",
    "……消失了……？",
    "7. [MARKER: Message] 喬喬莉娜「",
    "從剛才開始，精神就好像很不穩定呢$g",
    "這難道是病毒的影響嗎？",
    "8. [MARKER: Message] 奧斯卡「",
    "雖然知道是受了病毒的影響，",
    "但最重要的病毒，到底在哪裡啊……？",
    "9. [MARKER: Message] 以藏「",
    "\\S[3]……？",
    "這個氣息是……？",
    "10. [MARKER: Message] 丹迪「",
    "\\S[3]……\\S[1]在上面！！",
    "11. [MARKER: Message] 以藏「",
    "在那麼高的地方……要怎麼過去啊……？",
    "12. [MARKER: Message] 以藏「",
    "喬喬莉娜，能到那邊去嗎？",
    "13. [MARKER: Message] 喬喬莉娜「",
    "去是可以去，但我才不想聽你命令呢$g",
    "14. [MARKER: Message] 以藏「",
    "可惡，偏偏在這種時候……。",
    "15. [MARKER: Message] 奧斯卡「",
    "丹迪……拜託你了……。",
    "16. [MARKER: Message] 丹迪「",
    "\\S[3]……\\S[1]喬喬莉娜，",
    "拜託帶我們過去那邊……。",
    "17. [MARKER: Message] 喬喬莉娜「",
    "好的$g，丹迪大人$g$g",
    "18. [MARKER: Message] 以藏「",
    "啊，看到流漸了喔。",
    "19. [MARKER: Message] 喬喬莉娜「",
    "我就覺得有些不對勁$g",
    "這裡一定是流漸大人所描繪出來的，",
    "過去的記憶吧$g",
    "20. [MARKER: Message] 奧斯卡「",
    "過去的記憶……。",
    "這到底是什麼時候的記憶呢……？",
    "21. [MARKER: Message] 奧斯卡「",
    "不管怎麼看，這都只能理解為",
    "異常的狀況啊……。",
    "22. [MARKER: Message] DANDY「",
    "只能直接問他本人了……。",
    "23. [MARKER: Message] 喬喬莉娜「",
    "不愧是丹迪大人～$g",
    "真是好主意$g$g",
])

# Map0073 (精神世界脫逃)
write_translated("Map0073.txt.trans.txt", [
    "1. [MARKER: Message] 喬喬莉娜「",
    "糟糕了$g$g",
    "因為摧毀了病毒，",
    "流漸大人他本人要醒過來了！$g",
    "2. [MARKER: Message] 喬喬莉娜「",
    "得快點逃出去！！$g$g",
    "3. [MARKER: Message] 喬喬莉娜「",
    "嘿呀——！！",
    "蟲洞！！$g$g",
    "4. [MARKER: Message] 以藏「",
    "……唔……。",
    "我……\\.我們回來了嗎？",
    "5. [MARKER: Message] 奧斯卡「",
    "流漸的狀況怎麼樣了？",
    "6. [MARKER: Message] 喬喬莉娜「",
    "直接問他本人不就好了嗎$g",
])

print("Map0067-0073 done.")
