# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0074~0079"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0074 (流漸精神世界 - 病毒消滅與電腦託付)
write_translated("Map0074.txt.trans.txt", [
    "1. [MARKER: Message] 流漸「",
    "\\S[3]……咕……啊啊啊啊啊……！！",
    "2. [MARKER: Message] 以藏「",
    "你怎麼了……！？",
    "3. [MARKER: Message] 流漸「",
    "\\S[2]你們……這幫人……。",
    "快點……\\S[1]離開這裡……！！",
    "4. [MARKER: Message] 奧斯卡「",
    "那可不行，我們是為了解除病毒",
    "才進入你的精神世界的。",
    "5. [MARKER: Message] 喬喬莉娜「",
    "所以嘛，病毒你識相的話快點滾出來$g",
    "6. [MARKER: Message] DANDY「",
    "喂……\\. 我的台詞被搶了……。",
    "7. [MARKER: Message] 流漸「",
    "\\S[3]啊……\\S[2]啊啊啊啊啊……。",
    "8. [MARKER: Message] 流漸「",
    "\\S[3]說要消滅我……？\\|",
    "\\S[6]有意思……。",
    "9. [MARKER: Message] 奧斯卡「",
    "……流漸……！？",
    "這……這個聲音是……！！",
    "10. [MARKER: Message] 流漸「",
    "\\S[4]等我奪取了這小子的精神，\\. ",
    "就把你們的精神也一併吞噬掉！！",
    "11. [MARKER: Message] 病毒「",
    "\\S[4]這小子的精神力……\\|到底是……怎麼回事……。",
    "12. [MARKER: Message] 流漸「",
    "可……可惡……！！",
    "要消失了……！！！！",
    "13. [MARKER: Message] 奧斯卡「",
    "請告訴我！！",
    "你到底是何方神聖！！？",
    "14. [MARKER: Message] 以藏「",
    "你真的是這個世界的居民嗎……？",
    "15. [MARKER: Message] 流漸「",
    "\\S[2]……把這個……收下……。",
    "會有派上用場的時候……。",
    "16. [MARKER: Message] ",
    "　　　　獲得了行動電腦！！",
    "17. [MARKER: Message] 以藏「",
    "\\S[2]……………………………………。",
    "18. [MARKER: Message] 奧斯卡「",
    "這是……？",
])

# Map0076 (拿破崙的真面目與安德烈救場)
write_translated("Map0076.txt.trans.txt", [
    "1. [MARKER: Message] 拿破崙「",
    "奧斯卡，你對現在的法國",
    "有什麼看法……？",
    "2. [MARKER: Message] 奧斯卡「",
    "\\S[2]……\\S[1]您的意思是？",
    "3. [MARKER: Message] 拿破崙「",
    "因為瑪麗的任性，人們每天",
    "光是活下去就竭盡全力了……。",
    "4. [MARKER: Message] 拿破崙「",
    "孩子們像流浪狗一樣",
    "倒在路邊，村民們只能等待死亡……。",
    "5. [MARKER: Message] 拿破崙「",
    "我一定要改變這個國家！！",
    "6. [MARKER: Message] 拿破崙「",
    "為此……我需要你的幫助……。",
    "7. [MARKER: Message] 奧斯卡「",
    "\\S[2]……誒……？",
    "8. [MARKER: Message] 拿破崙「",
    "……你會幫我的吧……？",
    "9. [MARKER: Message] 奧斯卡「",
    "\\.……\\.……\\.……是的$g",
    "10. [MARKER: Message] 奧斯卡「",
    "拿破崙大人……我有事想問您……。",
    "11. [MARKER: Message] 拿破崙「",
    "什麼事……？\\|",
    "……那邊的那些人，是你的朋友嗎？",
    "12. [MARKER: Message] 奧斯卡「",
    "您知道一個叫作「流漸」的男人嗎？",
    "13. [MARKER: Message] 拿破崙「",
    "\\S[2]……\\S[1]那又怎麼了？",
    "14. [MARKER: Message] 奧斯卡「",
    "有人說您今天殺了那個男人，這\\S[3]……",
    "\\S[1]一定是騙人的吧！！！？",
    "15. [MARKER: Message] 拿破崙「",
    "\\S[2]……是誰……\\S[1]在胡說八道……？",
    "16. [MARKER: Message] 奧斯卡「",
    "果然是假的對吧！！",
    "……太好了……。",
    "17. [MARKER: Message] 拿破崙「",
    "\\S[2]那當然是騙人的啦\\S[4]……\\^",
    "18. [MARKER: Message] 以藏「",
    "奧斯卡！！",
    "19. [MARKER: Message] 奧斯卡「",
    "拿破崙大人……！！？",
    "20. [MARKER: Message] 以藏「",
    "喔喔喔喔喔喔喔喔……！？",
    "21. [MARKER: Message] 拿破崙「",
    "哈哈哈哈哈哈哈————！！！",
    "那傢伙早就被轟到時空的彼端去了！！！！！",
    "22. [MARKER: Message] 拿破崙「",
    "喂，JOKER！！！",
    "殺了這幫傢伙！！！",
    "23. [MARKER: Message] 拿破崙「",
    "給我把那台行動電腦摧毀掉！！！！",
    "24. [MARKER: Message] 奧斯卡「",
    "以藏……。",
    "25. [MARKER: Message] 奧斯卡「",
    "我們去北邊的巴士底監獄吧……。",
    "26. [MARKER: Message] 丹迪「",
    "我記得那裡應該有士兵駐守吧……。",
    "27. [MARKER: Message] 喬喬莉娜「",
    "用我的魔法把他們燒成焦炭也行啦……\\.\\^",
    "28. [MARKER: Message] 丹迪「",
    "不可以這樣做。",
    "29. [MARKER: Message] 奧斯卡「",
    "……總……總之先去北邊吧。",
    "30. [MARKER: Message] JOKER「",
    "……遵命……。",
    "31. [MARKER: Message] 奧斯卡「",
    "拿破崙大人……。",
    "\\S[2]這是假的吧………………。",
    "32. [MARKER: Message] 拿破崙「",
    "你只不過是一顆棄子而已啦……。",
    "33. [MARKER: Message] JOKER「",
    "嚯……DANDY。",
    "好久不見了呢……。",
    "34. [MARKER: Message] DANDY「",
    "別叫得那麼親熱……！！ JOKER！！！",
    "35. [MARKER: Message] DANDY「",
    "呵呵呵……我馬上就送你去陪那個叫以藏的傢伙……。",
    "36. [MARKER: Message] ？？？？「",
    "我可不會讓你們得逞的！！！！",
    "37. [MARKER: Message] 安德烈「",
    "剛才的話……我都聽到了！！！",
    "38. [MARKER: Message] 拿破崙「",
    "在哪裡聽到的？",
    "39. [MARKER: Message] 安德烈「",
    "\\C[5]你們這群傢伙，點燃了我的怒火！！",
    "嘗嘗我的憤怒吧！！！！",
    "40. [MARKER: Message] JOKER「",
    "區區一個存檔點風情的人……！！",
    "死吧！！！！！",
    "41. [MARKER: Message] 拿破崙「",
    "撤退！！！",
    "42. [MARKER: Message] 安德烈「",
    "以藏還活著喔……。",
    "一定……。",
    "43. [MARKER: Message] 奧斯卡「",
    "\\S[2]………………………………………………。",
    "44. [MARKER: Message] 安德烈「",
    "我接下來要踏上旅程了……。",
    "我一定會把以藏帶回來的！！",
    "45. [MARKER: Message] 安德烈「",
    "各位請潛入巴士底監獄吧。\\.",
    "為了不讓拿破崙他們逃掉。",
    "46. [MARKER: Message] 奧斯卡「",
    "巴士底監獄裡……",
    "到底有著什麼……？",
    "47. [MARKER: Message] 安德烈「",
    "那請用你自己的雙眼去確認吧……",
    "你一定能在那裡找到關於拿破崙的蛛絲馬跡的。",
])

# Map0078 (以藏視角 - 阻礙通行)
write_translated("Map0078.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "哎呀，這下過不去了呢……。",
    "2. [MARKER: Message] 以藏「",
    "哎呀，這下過不去了呢……。",
])

# Map0079 (核心電腦室 - 與 GODZILLER 的對話)
write_translated("Map0079.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "這就是所謂的主電腦了吧。",
    "2. [MARKER: Message] 確定要破壞嗎？",
    "3. [MARKER: Message] ",
    "　　　　　破壞了主電腦。",
    "4. [MARKER: Message] 以藏「",
    "好啦，回去找委託我做這種",
    "麻煩事的流漸那裡吧……。",
    "5. [MARKER: Message] 奧斯卡「",
    "嗯……？剛剛有什麼聲音響起嗎……？",
    "6. [MARKER: Message] DANDY「",
    "是不是那個行動電腦啊？",
    "7. [MARKER: Message] 以藏「",
    "……看來有什麼開關……。",
    "按按看吧……。",
    "8. [MARKER: Message] 喬喬莉娜「",
    "該不會要爆炸了吧$g",
    "9. [MARKER: Message] 行動電腦「",
    "\\C[5]喂——！！！ 快給我注意到啊～～～！！！",
    "10. [MARKER: Message] 行動電腦「",
    "\\C[5]雖說是待機狀態，但在系統休眠狀態下",
    "播放效果音可是很費勁的啊！！！",
    "11. [MARKER: Message] 以藏「",
    "\\S[2]……\\S[1]這什麼鬼啊……。",
    "12. [MARKER: Message] 行動電腦「",
    "太失禮了！！我就是本尊流漸啦！！",
    "被嚇到了吧！！\\S[2]……雖然只是拷貝版就是了……。",
    "13. [MARKER: Message] 以藏「",
    "這到底是怎麼回事啊，真是的……。",
    "長了一副像便當盒一樣的嘴臉……。",
    "14. [MARKER: Message] 行動電腦「",
    "我是行動電腦『GODZILLER』！",
    "你這個蠢貨！！",
    "15. [MARKER: Message] 行動電腦「",
    "我把我的個人人格移植到了這台掌上電腦裡！！",
    "為了把它壓縮在區區 16MB 的記憶體裡，",
    "我可是費了九牛二虎之力呢……。",
    "16. [MARKER: Message] 奧斯卡「",
    "那麼，剛才在那邊的那個傢伙是誰？",
    "難道那不是流漸本人嗎？",
    "17. [MARKER: Message] 行動電腦「",
    "那是複製人，我的複製人。",
    "18. [MARKER: Message] 喬喬莉娜「",
    "誰……？到底是為了什麼做出來的？$g",
    "19. [MARKER: Message] 行動電腦「",
    "天曉得……我哪會知道啊。",
    "20. [MARKER: Message] 奧斯卡「",
    "如果你是真正的流漸，",
    "你應該就能拆解「核彈」吧。",
    "21. [MARKER: Message] 行動電腦「",
    "也不是不行。",
    "前提是得有我原本的肉體才行。",
    "22. [MARKER: Message] 以藏「",
    "現在，你的肉體在哪裡？",
    "23. [MARKER: Message] 行動電腦「",
    "現在，應該被關在凡爾賽吧……。",
    "24. [MARKER: Message] 奧斯卡「",
    "凡爾賽……！！？",
    "巴士底監獄嗎……！！？",
    "25. [MARKER: Message] 行動電腦「",
    "沒錯。",
    "26. [MARKER: Message] 喬喬莉娜「",
    "犯罪者？$g",
    "27. [MARKER: Message] 行動電腦「",
    "才不是！！只是因為一些原因啦……。",
    "所以被抓起來了……。",
    "28. [MARKER: Message] 行動電腦「",
    "然後，我試圖將我的人格植入在那裡發現的複製人身上",
    "以此來控制他，",
    "並試圖救出我的本體……。",
    "29. [MARKER: Message] 行動電腦「",
    "但無奈那複製人意志也很頑強，",
    "一直沒辦法完全奪取他的控制權……。",
    "30. [MARKER: Message] 行動電腦「",
    "然後就在這個過程中中了病毒，",
    "當我覺得不妙的時候……。",
    "31. [MARKER: Message] 奧斯卡「",
    "我們就恰好出現了是吧。",
    "32. [MARKER: Message] 行動電腦「",
    "是的。",
    "33. [MARKER: Message] 行動電腦「",
    "恐怕那個複製人，已經被殺了吧。",
    "為了讓那些傢伙",
    "能從複製人身上奪走這台掌上電腦……。",
    "34. [MARKER: Message] 行動電腦「",
    "真是千鈞一髮啊……。",
    "35. [MARKER: Message] 奧斯卡「",
    "你說的「那些傢伙」到底是……。",
    "36. [MARKER: Message] 行動電腦「",
    "就是拿破崙喔。",
    "37. [MARKER: Message] 奧斯卡「",
    "胡說！！你這傢伙，那位大人怎麼可能會做",
    "這種事情！！！",
    "38. [MARKER: Message] 奧斯卡「",
    "給我收回那句話！！！",
    "39. [MARKER: Message] 行動電腦「",
    "就算叫我收回，但這就是事實啊……。",
    "40. [MARKER: Message] 行動電腦「",
    "啊，喂！！",
    "別關掉電源啊！！！",
    "41. [MARKER: Message] 以藏「",
    "\\S[2]奧斯卡……。",
    "42. [MARKER: Message] 奧斯卡「",
    "\\S[2]回凡爾賽吧……。",
    "43. [MARKER: Message] 以藏「",
    "這就是所謂的主電腦了吧。",
    "44. [MARKER: Message] 確定要破壞嗎？",
])

print("Map0074-0079 done.")
