# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0096~0100"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0096 (偏僻小村的日常與老頭們的相聲)
write_translated("Map0096.txt.trans.txt", [
    "1. [MARKER: Message] 老爺爺「",
    "看著池塘，心情就放鬆下來了呢～。",
    "2. [MARKER: Message] 耕田的男子「",
    "正在耕地中。",
    "3. [MARKER: Message] 牧牛人「",
    "一股牛屎味。",
    "4. [MARKER: Message] 村姑「",
    "真是個鄉下地方呢～～。",
    "5. [MARKER: Message] 老頭子A「",
    "這個村子終於恢復了一些活力呢～。",
    "6. [MARKER: Message] 老頭子B「",
    "是啊～",
    "7. [MARKER: Message] 老頭子C「",
    "因為14年前那場浩劫實在是太慘烈了嘛～",
    "8. [MARKER: Message] 老頭子D「",
    "好想喝茶喔。",
    "9. [MARKER: Message] 老頭子A「",
    "這個村子終於恢復了一些活力呢～。",
    "10. [MARKER: Message] 老頭子B「",
    "是啊～",
    "11. [MARKER: Message] 老頭子C「",
    "因為14年前那場浩劫實在是太慘烈了嘛～",
    "12. [MARKER: Message] 老頭子D「",
    "好想喝茶喔。",
    "13. [MARKER: Message] 老頭子A「",
    "這個村子終於恢復了一些活力呢～。",
    "14. [MARKER: Message] 老頭子B「",
    "是啊～",
    "15. [MARKER: Message] 老頭子C「",
    "因為14年前那場浩劫實在是太慘烈了嘛～",
    "16. [MARKER: Message] 老頭子D「",
    "好想喝茶喔。",
    "17. [MARKER: Message] 老頭子A「",
    "這個村子終於恢復了一些活力呢～。",
    "18. [MARKER: Message] 老頭子B「",
    "是啊～",
    "19. [MARKER: Message] 老頭子C「",
    "因為14年前那場浩劫實在是太慘烈了嘛～",
    "20. [MARKER: Message] 老頭子D「",
    "好想喝茶喔。",
    "21. [MARKER: Message] 老奶奶「",
    "這個村子在14年前被盜賊襲擊了呢～，",
    "當時戰死的年輕人們，現在就沉睡在這座墓碑下面喔……。",
    "22. [MARKER: Message] 村婦「",
    "住在對面帳篷裡的人，",
    "聽說是一位很厲害的格鬥家呢。",
    "但為什麼要住帳篷啊……。",
    "23. [MARKER: Message] 村姑「",
    "沒想到你會來這種偏僻的地方呢……。",
    "24. [MARKER: Message] 村姑「",
    "\\S[2]……？ \\S[1]",
    "你的眼睛……是紅色的呢。",
    "25. [MARKER: Message] 村姑「",
    "唔～……我總覺得",
    "好像在哪裡見過紅色眼睛的人呢～……。",
])

# Map0097 (以藏的夢境與媽媽的聲音)
write_translated("Map0097.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "\\S[2]……？\\. 這裡是……。",
    "2. [MARKER: Message] 奧斯卡「",
    "\\S[2]……以藏……？",
    "3. [MARKER: Message] 以藏「",
    "……媽媽……。",
])

# Map0098 (科洛愛的款待與以藏身世的暗示)
write_translated("Map0098.txt.trans.txt", [
    "1. [MARKER: Message] 女子「",
    "哎呀，你好啊。",
    "2. [MARKER: Message] 以藏「",
    "有……有什麼事嗎？",
    "3. [MARKER: Message] 女子「",
    "真少見呢……眼睛是紅色的孩子……。\\.",
    "吶，現在已經是傍晚了，你要不要在我們家留宿一晚？",
    "4. [MARKER: Message] [FACE: イゾウ, 1, Left, Normal] 以藏「",
    "5. [MARKER: Message] [FACE: イゾウ, 1, Left, Normal] 以藏「",
    "說得也是呢。\\.",
    "反正也沒地方住，",
    "那就恭敬不如從命囉？",
    "6. [MARKER: Message] [FACE: Erase] 女子「",
    "是嗎？\\. 願意留下來住嗎？\\.",
    "那我現在去準備，你先好好放鬆一下吧。",
    "7. [MARKER: Message] [FACE: Erase] ",
    "    就這樣，以藏一夥人在這裡留宿了一晚。",
    "8. [MARKER: Message] [FACE: Erase] 以藏「",
    "為什麼突然……。",
    "9. [MARKER: Message] [FACE: Erase] 女子「",
    "說得也是呢。\\. 突然被不認識的人邀請",
    "留宿，確實會想要推辭的吧。\\.",
    "如果以後有興趣的話，隨時再來喔。",
    "10. [MARKER: Message] [FACE: Erase] 女子「",
    "難道你是……。\\|",
    "不，\\.沒什麼，當我沒說吧……。",
])

# Map0099 (村長與格鬥家鮎的情報)
write_translated("Map0099.txt.trans.txt", [
    "1. [MARKER: Message] 村長「",
    "真高興你們能來到我們這偏僻的小村落。",
    "雖然這裡沒什麼特別好玩的地方，",
    "但請慢慢休息吧。",
    "2. [MARKER: Message] 村長「",
    "喔，你在科洛愛那邊聽說了這件事啊……。",
    "3. [MARKER: Message] 村長「",
    "說起來，最近在北美大陸那裡，",
    "好像能看到一些奇怪的東西……。",
    "4. [MARKER: Message] 奧斯卡「",
    "奇怪的東西？",
    "5. [MARKER: Message] 村長「",
    "住在這個村子裡的格鬥家「鮎」，",
    "曾經說過『看到了若隱若現的巨大城堡』。",
    "6. [MARKER: Message] 村長「",
    "我們雖然也去確認了，但當時",
    "根本就沒有什麼城堡的蹤影。",
    "7. [MARKER: Message] 以藏「",
    "那座城堡大概在什麼位置……？",
    "8. [MARKER: Message] 村長「",
    "這個嘛……",
    "從這裡往北走相當長的一段路吧。",
    "9. [MARKER: Message] 村長「",
    "但因為我們自己並沒有親眼見到那座城堡，",
    "所以無法給出詳細的資訊……。\\.",
    "我想你們還是直接去問「鮎」本人比較好喔。",
    "10. [MARKER: Message] DANDY「",
    "我們就去問問看吧……。",
    "多謝了，村長閣下。",
    "11. [MARKER: Message] 村長「",
    "若能幫上忙那就太好了。\\. ",
    "順便一提，「鮎」就住在這棟房子的隔壁。",
    "12. [MARKER: Message] 村長「",
    "你和鮎談過了嗎？",
    "13. [MARKER: Message] 侍從「",
    "聽說門口的魔法陣是拿來辟邪的喔。",
])

# Map0100 (特產商販)
write_translated("Map0100.txt.trans.txt", [
    "1. [MARKER: Message] 老爺爺「",
    "買點我們村子的特產去吧。",
    "2. [MARKER: Message] 老爺爺「",
    "謝謝你……。",
])

print("Map0096-0100 done.")
