# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0116~0120"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0116 (救出DANDY與JOKER的搶奪聖劍)
write_translated("Map0116.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "為什麼我要做這種粗活啊……。",
    "2. [MARKER: Message] 喬喬莉娜「",
    "這還用問嗎？當然 is 為了 DANDY 大人啊$g",
    "別抱怨了，快推啦$g",
    "3. [MARKER: Message] 以藏「",
    "好好好……。",
    "4. [MARKER: Message] 以藏「",
    "唔～～～～～～嗯！！",
    "5. [MARKER: Message] 以藏「",
    "呼————……累死了……。",
    "喂，DANDY！你也來幫忙啊！！",
    "6. [MARKER: Message] DANDY「",
    "知道了。",
    "7. [MARKER: Message] 以藏「",
    "額……喂……。",
    "8. [MARKER: Message] DANDY「",
    "好，要用力推囉！！",
    "9. [MARKER: Message] DANDY「",
    "你在幹什麼啊！！",
    "10. [MARKER: Message] 以藏「",
    "從對面用力推啊啊啊————！！！",
    "11. [MARKER: Message] 以藏「",
    "聽我口令，預備——推喔。",
    "\\S[2]預——\\.備——\\.推——\\.唷！！",
    "12. [MARKER: Message] 以藏「",
    "好極了————！！",
    "13. [MARKER: Message] DANDY「",
    "大家一起合力的話，總會有辦法的呢……。",
    "這就是友情的力量。",
    "14. [MARKER: Message] 以藏「",
    "你這傢伙……。",
    "15. [MARKER: Message] DANDY「",
    "嗨，我親愛的各位！！",
    "過得還好嗎？",
    "16. [MARKER: Message] 以藏「",
    "你還是一如既往的厚臉皮呢……。",
    "17. [MARKER: Message] 喬喬莉娜「",
    "啊～嗯$g$g DANDY大人——！！$g",
    "我再也不要離開您了～$g$g",
    "18. [MARKER: Message] ？？？？？「",
    "餵——！！ 你們在親熱個什麼勁啊！！！！",
    "19. [MARKER: Message] DANDY「",
    "姆！這聲音是 JOKER！！！",
    "20. [MARKER: Message] DANDY「",
    "從右邊推過來啊。",
    "21. [MARKER: Message] JOKER「",
    "喂！！！",
    "22. [MARKER: Message] DANDY「",
    "事到如今，你還有何貴幹 retreat 嗎！？",
    "23. [MARKER: Message] JOKER「",
    "把你手上的聖劍「德雷德諾特」交出來！！",
    "如果沒有那個，我可是會死的啊！！！！！",
    "24. [MARKER: Message] DANDY「",
    "嗚哇！",
    "你為什麼會知道聖劍的事情？！",
    "25. [MARKER: Message] JOKER「",
    "我早就知道啦！！就在那座王座的下面",
    "隱藏著它……。",
    "給我讓開！！！",
    "26. [MARKER: Message] DANDY「",
    "可惡，舊恨未消，休想輕易拿走它！",
    "想要過去的話，就先打倒我吧！！",
    "27. [MARKER: Message] JOKER「",
    "可惡，真是個冥頑不靈的大笨蛋！！！",
    "28. [MARKER: Message] ？？「",
    "找到你啦～～～～！！！！！",
    "29. [MARKER: Message] JOKER「",
    "你這傢伙……知道自己撞到的是誰……。",
    "30. [MARKER: Message] JOKER「",
    "嗝哇啊啊啊啊啊啊啊啊啊！！",
    "流漸！！！",
    "31. [MARKER: Message] 流漸「",
    "居然敢算計我！！你這個骷髏頭混蛋！！！",
    "32. [MARKER: Message] JOKER「",
    "噫————！！！",
    "DANDY！ 聖劍就先寄放在你那！！",
    "我遲早會來奪走的！！！ 告辭！！！",
    "33. [MARKER: Message] 流漸「",
    "啊，喂！ 別跑！！！",
    "34. [MARKER: Message] 以藏「",
    "這……這到底是搞什麼名堂啊……。",
    "35. [MARKER: Message] DANDY「",
    "流漸殿下出現的時機真是太完美了，",
    "幫大忙了呢……。",
    "我們趁現在把德雷德諾特拿到手吧。",
    "36. [MARKER: Message] 以藏「",
    "雖然搞不太懂，但總之",
    "那是個非常重要的東西對吧。",
    "37. [MARKER: Message] DANDY「",
    "就是這麼回事。 ",
    "德雷德諾特就在這座王座的下方。",
    "以藏殿下，麻煩你把它移開吧。",
    "38. [MARKER: Message] DANDY「",
    "你打算去哪裡啊，以藏殿下。",
    "德雷德諾特只可能在這邊喔。",
    "39. [MARKER: Message] DANDY「",
    "你打算去哪裡啊，以藏殿下。",
    "德雷德諾特只可能在這邊喔。",
    "40. [MARKER: Message] DANDY「",
    "你打算去哪裡啊，以藏殿下。",
    "德雷德諾特只可能在這邊喔。",
    "41. [MARKER: Message] DANDY「",
    "你打算去哪裡啊，以藏殿下。",
    "德雷德諾特只可能在這邊喔。",
    "42. [MARKER: Message] DANDY「",
    "你打算去哪裡啊，以藏殿下。",
    "德雷德諾特只可能在這邊喔。",
])

# Map0118 (獲得無畏聖劍與佐助的引路)
write_translated("Map0118.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "這把劍，插得還真是有模有樣的呢……。",
    "2. [MARKER: Message] DANDY「",
    "畢竟氣氛可是很重要的嘛。",
    "\\S[2]……\\S[1]那把劍，以藏殿下",
    "就由你來使用吧。",
    "3. [MARKER: Message] 以藏「",
    "可以嗎？對我來說，能免費拿到武器",
    "自然是再好不過了……。",
    "4. [MARKER: Message] DANDY「",
    "啊防禦力雖然很高，但我現在拿著它",
    "也派不上任何用場了。",
    "5. [MARKER: Message] 以藏「",
    "既然如此，那我就感激地收下囉。",
    "6. [MARKER: Message] ",
    "　　　　獲得了聖劍『德雷德諾特』！！",
    "7. [MARKER: Message] DANDY「",
    "接下來該怎麼辦？",
    "8. [MARKER: Message] 以藏「",
    "這還用說！當然是去救奧斯卡了！！",
    "9. [MARKER: Message] DANDY「",
    "但是……奧斯卡殿下到底在什麼地方……。",
    "10. [MARKER: Message] ？？？「",
    "關於那件事……",
    "就由在下來向各位說明吧……。",
    "11. [MARKER: Message] 以藏「",
    "哎呀……你不是那時候的……。",
    "12. [MARKER: Message] 佐助「",
    "在下佐助……。",
    "就由在下來說明當時的狀況吧。",
    "13. [MARKER: Message] 佐助「",
    "在那之後，流漸雖然把 JOKER 打得半死，",
    "但也因為當時的衝擊，我們三個人",
    "都被震得各奔東西了……。",
    "14. [MARKER: Message] 佐助「",
    "但是，有一件事在下是可以確定的，",
    "那就是奧斯卡殿下目前就在凡爾賽的『拿破崙生態研究所』",
    "裡面！！",
    "15. [MARKER: Message] 以藏「",
    "謝啦，能知道這一點",
    "就已經幫大忙了。",
    "16. [MARKER: Message] 佐助「",
    "在下未能保護好那位大人的說……。",
    "非常抱歉……。",
    "17. [MARKER: Message] 以藏「",
    "………………我們朝凡爾賽出發！",
])

# Map0119 (出發提示)
write_translated("Map0119.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "我們走！！",
    "2. [MARKER: Message] 以藏「",
    "我們走！！",
])

# Map0120 (奧斯卡身世揭曉與世界局勢劇變)
write_translated("Map0120.txt.trans.txt", [
    "1. [MARKER: Message] ナポレオン「",
    "\\S[2]……嘰……嘰嘰……嘎嘎……。",
    "2. [MARKER: Message] 安德烈「",
    "你沒事吧？奧斯卡。",
    "3. [MARKER: Message] 奧斯卡「",
    "\\S[2]……啊……。",
    "4. [MARKER: Message] 安德烈「",
    "以藏他們很快就會來了。",
    "來救你喔……。",
    "5. [MARKER: Message] 安德烈「",
    "那，老夫就先告辭啦……。",
    "6. [MARKER: Message] 奧斯卡「",
    "請等一下！！！",
    "7. [MARKER: Message] 奧斯卡「",
    "\\S[2]………………。",
    "8. [MARKER: Message] 奧斯卡「",
    "以藏……你來救我了嗎……？",
    "9. [MARKER: Message] 以藏「",
    "你在說什麼啊？",
    "你可是我的『委託人』不是嗎。",
    "10. [MARKER: Message] 奧斯卡「",
    "\\S[2]……是嗎……。",
    "謝謝你……。",
    "11. [MARKER: Message] 奧斯卡「",
    "\\S[2]呼啊，睡得真舒服……。",
    "12. [MARKER: Message] 拿破崙「",
    "你醒了嗎，我可愛的姑娘……。",
    "13. [MARKER: Message] 奧斯卡「",
    "這……這是什麼！！？",
    "14. [MARKER: Message] 拿破崙「",
    "有什麼好驚訝的？",
    "是驚訝於自己被關起來了嗎？",
    "15. [MARKER: Message] 拿破崙「",
    "\\S[2]還是說……。",
    "16. [MARKER: Message] 拿破崙「",
    "是因為這些傢伙呢……？",
    "17. [MARKER: Message] 奧斯卡「",
    "\\S[2]……她們是我的……\\S[1]複製人嗎？",
    "18. [MARKER: Message] 拿破崙「",
    "\\S[2]呵呵呵……。",
    "19. [MARKER: Message] 拿破崙「",
    "\\S[2]呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵呵……。",
    "20. [MARKER: Message] 拿破崙「",
    "\\S[2]哈哈哈哈哈哈哈哈哈！！！",
    "\\S[1]你在說什麼呢？『原型機』！！",
    "21. [MARKER: Message] 拿破崙「",
    "\\S[2]……不……\\S[1]是失敗品啦！！！",
    "22. [MARKER: Message] 奧斯卡「",
    "你說什麼！！！？",
    "23. [MARKER: Message] 拿破崙「",
    "就實話告訴你吧……。",
    "24. [MARKER: Message] 拿破崙「",
    "你，是我製造出來的",
    "『\\C[4]仿生變異體\\C[0]』！！",
    "25. [MARKER: Message] 奧斯卡「",
    "\\S[2]……。",
    "26. [MARKER: Message] 拿破崙「",
    "本來是為了讓我征服世界的計畫能更順利進行而製造的……。",
    "\\S[2]沒想到，居然會變成這樣……。",
    "27. [MARKER: Message] 拿破崙「",
    "我身後的這些傢伙，是連『自我』都沒有的",
    "失敗品……。",
    "28. [MARKER: Message] 拿破崙「",
    "\\S[2]就跟你一樣呢……。",
    "29. [MARKER: Message] 奧斯卡「",
    "\\S[2]僅僅是為了那種目的……",
    "我才被製造出來的嗎……？",
    "30. [MARKER: Message] 拿破崙「",
    "那倒也不全是……",
    "你還有著各種用處喔？",
    "31. [MARKER: Message] 拿破崙「",
    "像是……",
    "當本大爺發洩的○×$g之類的啦！！！",
    "32. [MARKER: Message] 拿破崙「",
    "\\S[2]……嗯？",
    "33. [MARKER: Message] 奧斯卡「",
    "好，我們走吧！！",
    "34. [MARKER: Message] 以藏「",
    "\\S[2]……去哪裡……？",
    "35. [MARKER: Message] 奧斯卡「",
    "\\S[2]……回家吧……。",
    "36. [MARKER: Message] ",
    "　　　　　　　　\\S[2]雖然很想回家，",
    "　　　　但因為凡爾賽已經不復存在，",
    "37. [MARKER: Message] ",
    "　　\\S[2]於是便暫時借住在丹迪的家中。",
    "38. [MARKER: Message] ",
    "　　　　　　　　\\S[2]然而……。",
    "39. [MARKER: Message] ",
    "　　　　　　　\\S[2]在此期間，英國仍繼續",
    "　　　　進行著侵略世界的野心……。",
    "40. [MARKER: Message] ",
    "　　　　　\\S[2]新日本、中國、蘇聯",
    "　　　　　\\S[4]……以及法國相繼滅亡……。",
    "41. [MARKER: Message] ",
    "　　　　　　\\S[2]如今，有能力與英國抗衡的戰力，",
    "　　　　　世界各地已經不復存在……。",
    "42. [MARKER: Message] ",
    "　　　　　　　　　\\S[2]唯獨只有一個……。",
    "43. [MARKER: Message] ",
    "　　　\\S[2]那就是『拿破崙帝國』……。",
    "44. [MARKER: Message] ",
    "　　　 \\S[2]拿破崙帝國與英國……。",
    "　　　　　　這兩大強權的戰爭……。",
    "45. [MARKER: Message] ",
    "　　　　\\S[2]起初，世人皆以為擁有『核彈』的",
    "　　　英國將會佔據絕對的優勢……\\.\\S[5]但是……。",
    "46. [MARKER: Message] ",
    "　　 \\S[2]令人震驚的是，拿破崙帝國竟也",
    "　　　　　研發完成了『核彈』…… Cliffhanger",
    "47. [MARKER: Message] ",
    "　　\\S[2]這使得英國與拿破崙帝國的交戰，",
    "　　　　在一段時間內陷入了膠著狀態……。",
    "48. [MARKER: Message] 　　\\S[2]然而，在綜合戰力上落後於拿破崙帝國的",
    "　　　英國，終究悲哀地以「合併」的名義，\\.",
    "　　　　　　被拿破崙帝國給吞併吸收了。",
    "49. [MARKER: Message] ",
    "　　　　　　　\\S[5]至此……世界徹底被",
    "　　　『拿破崙帝國』所征服……。",
    "50. [MARKER: Message] ",
    "　　　\\S[2]但是……拿破崙帝國的侵略狂潮……。",
    "　　　　　卻反而變得越發瘋狂激烈……。",
    "51. [MARKER: Message] ",
    "　　　　　　　　　\\S[5]那模樣……",
    "　　\\S[4]就彷彿，是要將整個世界都引向毀滅一般……。",
])

print("Map0116-0120 done.")
