# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0148~0151"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0148 (印度民居與咖哩倉庫)
write_translated("Map0148.txt.trans.txt", [
    "1. [MARKER: Message] 倉庫守衛「",
    "這個倉庫裡的糧食，全部都是里德先生送給我們的喔。",
    "2. [MARKER: Message] 老奶奶「",
    "咖哩的原材料，是一種叫作薑黃（鬱金）的香料喔！",
    "3. [MARKER: Message] ",
    "　　　　　裡面裝著滿滿的褐色薑黃粉！",
    "4. [MARKER: Message] ",
    "　　　　　裡面裝著滿滿的褐色薑黃粉！",
    "5. [MARKER: Message] ",
    "　　　　　裡面裝著滿滿的褐色薑黃粉！",
    "6. [MARKER: Message] ",
    "　　　　　裡面裝著滿滿的褐色薑黃粉！",
    "7. [MARKER: Message] ",
    "　　　　　裡面裝著滿滿的褐色薑黃粉！",
    "8. [MARKER: Message] 咖哩大師「",
    "老夫就是咖哩大師！",
    "就賞賜你老夫親自熟成了三個月的特製咖哩吧！",
    "9. [MARKER: Message] ",
    "　　　　　　　獲得了大師咖哩！",
    "10. [MARKER: Message] 咖哩大師「",
    "已經賣完囉。",
    "11. [MARKER: Message] 次男「",
    "肚子好餓喔～。",
    "12. [MARKER: Message] 長男「",
    "那邊的木桶是我們用來囤積咖哩的喔。",
    "13. [MARKER: Message] 三男「",
    "咖………………咖哩給我啊啊啊啊！",
    "14. [MARKER: Message] 老爹「",
    "這小鬼因為吃了太多咖哩，",
    "都得咖哩中毒症了！",
    "我們家暫時要實行禁咖哩令！",
    "15. [MARKER: Message] 大嬸「",
    "肚子會餓就代表你還沒超越凡俗，",
    "像我三天不吃不喝也無關痛癢！",
    "16. [MARKER: Message] 倉庫看管員「",
    "這上面是倉庫喔。",
    "17. [MARKER: Message] ",
    "　　　　　　傳來了一股好聞的咖哩香味！",
    "18. [MARKER: Message] ",
    "　　　　　　傳來了一股好聞的咖哩香味！",
    "19. [MARKER: Message] ",
    "　　　　　　傳來了一股好聞的咖哩香味！",
    "20. [MARKER: Message] ",
    "　　　　　　傳來了一股好聞的咖哩香味！",
    "21. [MARKER: Message] ",
    "　　　　　　傳來了一股好聞的咖哩香味！",
    "22. [MARKER: Message] ",
    "　　　　　　傳來了一股好聞的咖哩香味！",
    "23. [MARKER: Message] ",
    "　　　　　　裡面裝著滿滿的白米！",
    "24. [MARKER: Message] ",
    "　　　　　　裡面裝著滿滿的白米！",
    "25. [MARKER: Message] ",
    "　　　　　　裡面裝著滿滿的白米！",
    "26. [MARKER: Message] ",
    "　　　　　　裡面裝著滿滿的白米！",
    "27. [MARKER: Message] ",
    "　　　　　　裡面裝著滿滿的白米！",
    "28. [MARKER: Message] ",
    "　　　　　　裡面裝著滿滿的白米！",
    "29. [MARKER: Message] ",
    "　　　　　　裡面裝著滿滿的白米！",
])

# Map0149 (印度皇宮咖哩神教)
write_translated("Map0149.txt.trans.txt", [
    "1. [MARKER: Message] 國王「",
    "給老子吃咖哩！！",
    "2. [MARKER: Message] 修行僧「",
    "身為印度教教祖也是我們國王，",
    "『蒙德・拉・咖哩』國王的教義",
    "是非常嚴格的……。",
    "3. [MARKER: Message] 修行僧「",
    "國王說『印度教的真諦在於咖哩！』，",
    "所以我們每天三餐都必須吃咖哩……。",
    "4. [MARKER: Message] 修行僧「",
    "再怎麼喜歡吃的東西，",
    "每天三餐一直吃也是很痛苦的啊……。",
    "5. [MARKER: Message] 修行僧「",
    "我正在練習空中漂浮……。",
    "6. [MARKER: Message] 師範「",
    "將印度教修行到極致的人，",
    "就能像這樣飄浮在空中喔。",
    "7. [MARKER: Message] 修行僧「",
    "咕……看來我的修行還遠遠不夠啊……。",
    "再來一次！",
    "8. [MARKER: Message] 大臣「",
    "您今天吃過咖哩了嗎？",
    "9. [MARKER: Message] 愛牛男子「",
    "牛是神聖的生物，",
    "絕對不可以欺負牛隻喔。",
    "絕對不行喔。",
    "10. [MARKER: Message] 爺爺「",
    "吃咖哩度過了無數載的歲月……",
    "至今卻依舊無法徹底參透咖哩的真諦。",
    "真是高深莫測……",
    "11. [MARKER: Message] 奶奶「",
    "果然還是放到第二天的咖哩最美味了。",
    "慢火細細熬煮……",
    "哎呀……光是想想就興奮得顫抖呢。",
    "12. [MARKER: Message] ",
    "　　　這是印度式廁所，裡面有一隻豬呢。",
    "13. [MARKER: Message] 健康男子「",
    "用印度式廁所，今天也是健康滿分！",
    "14. [MARKER: Message] 愛修行的女子「",
    "慢跑修行！",
    "流完汗之後吃的咖哩，真是太美味了！",
])

# Map0150 (印度市區民居)
write_translated("Map0150.txt.trans.txt", [
    "1. [MARKER: Message] 一般人「",
    "真是惡趣味的圖案設計呢……。",
    "2. [MARKER: Message] 男子「",
    "你知道為什麼牛在我們這裡會是神聖的生物嗎？",
    "3. [MARKER: Message] 男子「",
    "那是因為牛奶和咖哩超級搭的呀。",
    "難道還有比這更合理的理由嗎？",
])

# Map0151 (法國港口售票處)
write_translated("Map0151.txt.trans.txt", [
    "1. [MARKER: Message] 售票員「",
    "我們這裡目前正在發售",
    "前往英國的船票。",
    "2. [MARKER: Message] 售票員「",
    "船票的價格是 50 D。",
    "請問您要購買嗎？",
    "3. [MARKER: Message] 售票員「",
    "那麼，請收下您的船票。",
    "4. [MARKER: Message] ",
    "　　　　　　　獲得了乘船票！",
    "5. [MARKER: Message] 售票員「",
    "船馬上就要出發了，請您抓緊時間。",
    "6. [MARKER: Message] 售票員「",
    "您的持有金好像不夠呢……。",
    "7. [MARKER: Message] 售票員「",
    "期待您的再次光臨。",
    "8. [MARKER: Message] 售票員「",
    "期待您的再次光臨。",
    "9. [MARKER: Message] 售票員「",
    "您似乎已經持有船票了呢。\\.",
    "非常感謝您的購買。",
    "10. [MARKER: Message] 售票員「",
    "目前沒有開往英國的船隻，",
    "所以目前暫不售票。",
    "敬請見諒。",
    "11. [MARKER: Message] 售票員「",
    "目前英國那邊已經不允許任何船隻入港了。",
    "12. [MARKER: Message] 男子「",
    "我過一陣子要去英國出差呢……。",
    "聽說那邊規模很大，不知道安不安全啊……。",
])

print("Map0148-0151 done.")
