# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0156~0159"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0156 (巨大飛空艇新日本號與突擊準備)
write_translated("Map0156.txt.trans.txt", [
    "1. [MARKER: Message] 以藏「",
    "流漸……這裡到底是……。",
    "2. [MARKER: Message] 流漸「",
    "喔，是你們啊。",
    "3. [MARKER: Message] 流漸「",
    "給老子好好吃驚一下吧！！\\.我竟然只花了一天時間，",
    "就把新日本改造為巨大飛空艇了！\\.",
    "這樣一來就能直接突入美國了！",
    "4. [MARKER: Message] 流漸「",
    "\\C[11]主砲採用了反質子雷射！！\\.",
    "而且船身大量使用了具有自我再生能力的",
    "高級有機素材！",
    "5. [MARKER: Message] 流漸「",
    "\\C[11]內部甚至實現了由我編寫的電腦程序",
    "進行完全環境控制功能！！",
    "6. [MARKER: Message] 流漸「",
    "\\C[11]而最厲害的，就是引擎",
    "搭載了既乾淨且超高輸出的",
    "反物質引擎！！",
    "7. [MARKER: Message] 流漸「",
    "\\S[2]……\\S[1]不過，問題是做為引擎燃料的",
    "反物質我們目前沒有呢……。",
    "8. [MARKER: Message] 喬喬莉娜「",
    "那不就完全沒用嘛$g",
    "9. [MARKER: Message] DANDY「",
    "\\S[2]反物質嗎……。\\S[1]\\.",
    "我倒是知道哪裡有……。",
    "10. [MARKER: Message] オスカー「",
    "真的嗎！！？",
    "11. [MARKER: Message] DANDY「",
    "\\S[2]……啊啊……。",
    "12. [MARKER: Message] 流漸「",
    "莫比烏斯之刃找到了嗎？",
    "13. [MARKER: Message] 以藏「",
    "正如你所期望的，",
    "我們把莫比烏斯之刃帶回來了。",
    "14. [MARKER: Message] 流漸「",
    "喔，回來了嗎。意外的還挺快的呢。",
    "15. [MARKER: Message] 以藏「",
    "……那麼，\\.用這個就可以了吧？",
    "16. [MARKER: Message] 流漸「",
    "\\S[3]嗯……\\S[2]不調查看看的話還不知道……。\\.",
    "\\S[1]稍微等一下，\\.馬上就好了。",
    "17. [MARKER: Message] 流漸「",
    "這無庸置疑，確實是反物質！！",
    "18. [MARKER: Message] 以藏「",
    "\\>太快了吧！！\<",
    "19. [MARKER: Message] 流漸「",
    "這樣就能突入美國了！",
    "我們這邊的準備工作早就完成了！！",
    "你們那邊準備好後，就來叫我吧！",
    "20. [MARKER: Message] ",
    "以藏裝備的莫比烏斯之刃已被卸下，",
    "　　　　請重新裝備其他武器。",
    "21. [MARKER: Message] 流漸「",
    "準備都妥當了嗎？",
    "22. [MARKER: Message] 以藏「",
    "沒問題，流漸。\\.朝著美國出發吧！！",
    "23. [MARKER: Message] 流漸「",
    "了解！",
    "24. [MARKER: Message] 流漸「",
    "Windoms Re！！\\.發動準備！！",
    "25. [MARKER: Message] 系統電腦「",
    "了解！！",
    "26. [MARKER: Message] 系統電腦「",
    "引擎出力 50%。",
    "隨時可以出航！",
    "27. [MARKER: Message] 流漸「",
    "以藏，下達發進命令吧……。",
    "28. [MARKER: Message] 以藏「",
    "居然由我來說嗎！？",
    "29. [MARKER: Message] 奧斯卡「",
    "拜託你了，以藏。",
    "30. [MARKER: Message] 以藏「",
    "\\S[2]新日本號……\\.",
    "\\>\\C[5]出航！！！！！\<",
    "31. [MARKER: Message] 系統電腦「",
    "遵命！！！！！",
    "32. [MARKER: Message] 流漸「",
    "什麼時候準備好，再來跟我打招呼吧。",
    "33. [MARKER: Message] 流漸「",
    "有發現什麼線索嗎？",
    "34. [MARKER: Message] ",
    "　　　以藏向流漸講述了在以藏村莊打聽到的情報。",
    "35. [MARKER: Message] 流漸「",
    "哦……在這座大陸的東北部嗎。\\.",
    "Re，檢索一下那個坐標。",
    "36. [MARKER: Message] 系統電腦「",
    "了解。",
    "37. [MARKER: Message] 系統電腦「",
    "在美國大陸東北部，偵測到大規模的時空扭曲。",
    "推測為敵方的大本營。",
    "38. [MARKER: Message] 流漸「",
    "這花了不少時間呢……。\\.",
    "看來對方是用強化的 DS 障壁進行了隱蔽吧。",
    "39. [MARKER: Message] 流漸「",
    "你覺得呢？以本艦的裝甲強度可以強行突破嗎？",
    "40. [MARKER: Message] 系統電腦「",
    "機率大概是一半一半吧。",
    "41. [MARKER: Message] 流漸「",
    "既然如此，你們打算怎麼辦？\\.",
    "恐怕一旦決定突入，就沒有回頭路可以走了。",
    "42. [MARKER: Message] [FACE: イゾウ, 1, Left, Normal] 以藏「",
    "43. [MARKER: Message] [FACE: イゾウ, 1, Left, Normal] 以藏「",
    "真是愚蠢的問題呢，當然是突擊了。",
    "44. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "都走到這一步了，已經沒有理由退縮了。",
    "45. [MARKER: Message] [FACE: Erase] DANDY「",
    "同意。",
    "46. [MARKER: Message] [FACE: Erase] 喬喬莉娜「",
    "喬喬莉娜不管去哪裡，都會跟隨 DANDY 大人的$g$g",
    "47. [MARKER: Message] [FACE: Erase] 流漸「",
    "\\S[2]……\\>好！\\<\.\\S[1]",
    "Windoms Re！護盾全開突擊！！\\.",
    "在接觸的瞬間，用主砲齊射在障壁上轟出一個洞來！",
    "48. [MARKER: Message] [FACE: Erase] 系統電腦「",
    "了解！",
    "49. [MARKER: Message] [FACE: Erase] 以藏「",
    "這是最後的戰鬥了。\\.我先做好萬全的準備！",
    "50. [MARKER: Message] [FACE: Erase] 流漸「",
    "是嗎，不過那些傢伙",
    "可不會一直站在那裡等我們喔。\\.",
    "請盡快做好出征的準備吧。",
    "51. [MARKER: Message] [FACE: Erase] 流漸「",
    "準備妥當了嗎？",
    "52. [MARKER: Message] [FACE: イゾウ, 1, Left, Normal] 以藏「",
    "53. [MARKER: Message] [FACE: イゾウ, 1, Left, Normal] 以藏「",
    "該做的準備都已經做好了！",
    "出發吧，流漸！",
    "54. [MARKER: Message] [FACE: Erase] 奧斯卡「",
    "都走到這一步了，已經沒有理由退縮了。",
    "55. [MARKER: Message] [FACE: Erase] DANDY「",
    "同意。",
    "56. [MARKER: Message] [FACE: Erase] 喬喬莉娜「",
    "喬喬莉娜不管去哪裡，都會跟隨 DANDY 大人的$g$g",
    "57. [MARKER: Message] [FACE: Erase] 流漸「",
    "\\S[2]……\\>好！\\<\.\\S[1]",
    "Windoms Re！護盾全開突擊！！\\.",
    "在接觸的瞬間，用主砲齊射在障壁上轟出一個洞來！",
    "58. [MARKER: Message] [FACE: Erase] 系統電腦「",
    "了解！",
    "59. [MARKER: Message] [FACE: Erase] 以藏「",
    "還沒有完全準備好……。",
    "60. [MARKER: Message] [FACE: Erase] 流漸「",
    "是嗎，不過那些傢伙",
    "可不會一直站在那裡等我們喔。\\.",
    "請盡快做好出征的準備吧。",
    "61. [MARKER: Message] [FACE: Erase] 鮎「",
    "哇……這地方還真厲害呢……。\\.",
    "沒想到在這座大陸上居然有這種科技……？",
    "62. [MARKER: Message] [FACE: Erase] 男子「",
    "在你們去尋找那個莫比什麼魔劍的期間，",
    "那邊那位叫流漸的人，似乎從世界各地",
    "召集了不少人才過來呢。",
    "63. [MARKER: Message] [FACE: Erase] 男子「",
    "我就是其中一個啦。",
    "64. [MARKER: Message] [FACE: Erase] 男子「",
    "其他人現在都在地下都市，",
    "你們也可以順便去見一見他們嘛？",
])

# Map0157 (飛空艇廁所)
write_translated("Map0157.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　因為是剛造好沒多久的，看起來亮晶晶呢！",
    "2. [MARKER: Message] ",
    "　　竟然在馬桶的裡面獲得了『超強力馬達』！",
    "3. [MARKER: Message] ",
    "　　因為是剛造好沒多久的，看起來亮晶晶呢！",
])

# Map0158 (飛空艇導航與埃及魔劍魔劍位置)
write_translated("Map0158.txt.trans.txt", [
    "1. [MARKER: Message] 男子「",
    "就是這個位置。\\.",
    "需要我幫您在地上標記出來嗎？",
    "2. [MARKER: Message] 男子「",
    "\\S[2]…………\\S[1]好的，\\.已經標記完了。\\.",
    "只要打開『導航儀』，就可以隨時",
    "確認埃及的具體位置了。",
    "3. [MARKER: Message] 男子「",
    "……那麼，接下來就拜託各位了。",
    "4. [MARKER: Message] DANDY「",
    "總之，我們先前往那裡吧。\\.",
    "那裡封印著據說連時空都能斬斷的魔劍『莫比烏斯之刃』……。",
    "5. [MARKER: Message] DANDY「",
    "為了以防萬一，先在導航儀上標記起來吧？",
    "6. [MARKER: Message] DANDY「",
    "\\S[2]…………\\S[1]好，\\.這樣就可以了。",
    "7. [MARKER: Message] 流漸「",
    "喔～斬斷時空啊……。",
    "看來無庸置疑，那把劍的動力源就是反物質呢。\\.",
    "話說回來，你為什麼會知道那種事情？",
    "8. [MARKER: Message] DANDY「",
    "\\S[2]……。",
    "9. [MARKER: Message] 以藏（",
    "\\C[1]能斬斷時空的魔劍……？",
    "10. [MARKER: Message] 奧爾貝「",
    "就像俺的哥哥們切開時空",
    "從這個世界逃出去了一樣，",
    "我們大家也一定能逃出去的，一起加油吧～。",
    "11. [MARKER: Message] 以藏「",
    "那種事情怎樣都好啦。",
    "好啦，\\.快點去把那個魔劍找回來，",
    "然後一口氣衝進美國吧！",
    "12. [MARKER: Message] DANDY「",
    "感激不盡……。",
    "13. [MARKER: Message] 奧斯卡＆喬喬莉娜「",
    "\\S[3]……？",
    "14. [MARKER: Message] 流漸「",
    "……也是呢，\\.嘛，算啦。\\.",
    "那麼你們就負責去把那把『莫比烏斯之刃』",
    "給帶回來吧。",
    "15. [MARKER: Message] 流漸「",
    "去到下個房間的西側有傳送裝置，",
    "從那裡應該能返回以前的新日本居民區。",
    "16. [MARKER: Message] 以藏「",
    "好，我們走吧。",
])

# Map0159 (封印魔劍的丹迪試煉門)
write_translated("Map0159.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　被某種神祕的奇妙力量保護著……。",
    "2. [MARKER: Message] 以藏「",
    "一上來就是緊閉的門嗎……。",
    "這要怎麼打開啊……？",
    "3. [MARKER: Message] DANDY「",
    "這裡如果不用我的絕招的話，是打不開的設計。",
    "4. [MARKER: Message] DANDY「",
    "\\S[2]……打個比方……。",
    "5. [MARKER: Message] DANDY「",
    "就是這樣一回事。",
    "6. [MARKER: Message] 以藏「",
    "哼……那麼，這裡就只能",
    "交給 DANDY 來想辦法了呢。",
    "7. [MARKER: Message] 喬喬莉娜「",
    "看來你這傢伙已經沒用了呢$g",
    "8. [MARKER: Message] 以藏「",
    "\\S[2]\\C[5]……宰了你喔……。",
    "9. [MARKER: Message] ",
    "　　　被某種神祕的奇妙力量保護著……。",
    "10. [MARKER: Message] DANDY「",
    "唔喔！打不開！！",
    "11. [MARKER: Message] 以藏「",
    "既然只有你才能打開，那接下來要怎麼辦啊……。",
    "12. [MARKER: Message] DANDY「",
    "看來我，修行還遠遠不夠啊……。",
    "13. [MARKER: Message] 以藏「",
    "也就是說，只用『丹迪神拳』是不夠格打開這扇門的囉。",
    "先去稍微修行一下再來吧……。",
    "14. [MARKER: Message] DANDY「",
    "唔喔！打不開！！",
    "15. [MARKER: Message] 以藏「",
    "既然只有你才能打開，那接下來要怎麼辦啊……。",
    "16. [MARKER: Message] DANDY「",
    "看來我，修行還遠遠不夠啊……。",
    "17. [MARKER: Message] 以藏「",
    "也就是說，只用『丹迪神拳』和『丹迪神踢』是不夠格打開的囉。",
    "先去稍微修行一下再來吧……。",
    "18. [MARKER: Message] DANDY「",
    "唔喔！打不開！！",
    "19. [MARKER: Message] 以藏「",
    "既然只有你才能打開，那接下來要怎麼辦啊……。",
    "20. [MARKER: Message] DANDY「",
    "看來我，修行還遠遠不夠啊……。",
    "21. [MARKER: Message] 以藏「",
    "也就是說，只用『丹迪神拳』、『丹迪神踢』和『丹迪勾拳』是不夠格打開的囉。",
    "先去稍微修行一下再來吧……。",
    "22. [MARKER: Message] DANDY「",
    "唔喔！打不開！！",
    "23. [MARKER: Message] 以藏「",
    "既然只有你才能打開，那接下來要怎麼辦啊……。",
    "24. [MARKER: Message] DANDY「",
    "看來我，修行還遠遠不夠啊……。",
    "25. [MARKER: Message] 以藏「",
    "也就是說，只用『丹迪神拳』是不夠格打開這扇門的囉。",
    "先去稍微修行一下再來吧……。",
    "26. [MARKER: Message] DANDY「",
    "唔喔！打不開！！",
    "27. [MARKER: Message] 以藏「",
    "既然只有你才能打開，那接下來要怎麼辦啊……。",
    "28. [MARKER: Message] DANDY「",
    "看來我，修行還遠遠不夠啊……。",
    "29. [MARKER: Message] 以藏「",
    "也就是說，只用『丹迪神拳』和『丹迪神踢』是不夠格打開的囉。",
    "先去稍微修行一下再來吧……。",
    "30. [MARKER: Message] DANDY「",
    "唔喔！打不開！！",
    "31. [MARKER: Message] 以藏「",
    "既然只有你才能打開，那接下來要怎麼辦啊……。",
    "32. [MARKER: Message] DANDY「",
    "看來我，修行還遠遠不夠啊……。",
    "33. [MARKER: Message] 以藏「",
    "也就是說，只用『丹迪神拳』、『丹迪神踢』和『丹迪勾拳』是不夠格打開的囉。",
    "先去稍微修行一下再來吧……。",
    "34. [MARKER: Message] DANDY「",
    "看來全部都順利打開了呢……。\\.呼……。",
    "35. [MARKER: Message] 以藏「",
    "我從很久以前就一直很想問了，",
    "DANDY，你絕招裡出現的那個男人到底是誰啊……？",
    "36. [MARKER: Message] DANDY「",
    "那就是我。……或者說，是我年輕時的姿態吧。",
    "因為那些必殺技，是將我的精神具現化之後釋放的招式呢。",
    "37. [MARKER: Message] 以藏「",
    "哼……真是挺方便的招式呢……。",
    "38. [MARKER: Message] 以藏「",
    "一上來就是緊閉的門嗎……。",
    "這要怎麼打開啊……？",
    "39. [MARKER: Message] DANDY「",
    "這裡如果不用我的絕招的話，是打不開的設計。",
    "40. [MARKER: Message] DANDY「",
    "\\S[2]……打個比方……。",
    "41. [MARKER: Message] DANDY「",
    "就是這樣一回事。",
    "42. [MARKER: Message] 以藏「",
    "哼……那麼，這裡就只能",
    "交給 DANDY 來想辦法了呢。",
    "43. [MARKER: Message] 喬喬莉娜「",
    "看來你這傢伙已經沒用了呢$g",
    "44. [MARKER: Message] 以藏「",
    "\\S[2]\\C[5]……宰了你喔……。",
])

print("Map0156-0159 done.")
