# -*- coding: utf-8 -*-
"""翻譯寫入 - Map0175~0180"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from write_translation import write_translated

# Map0175 (核彈室與尋找流漸的由來)
write_translated("Map0175.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　被嚴密地鎖上了，看來絕對是打不開的。",
    "2. [MARKER: Message] ",
    "　　被嚴密地鎖上了，看來絕對是打不開的。",
    "3. [MARKER: Message] 以藏「",
    "是這個嗎……？",
    "4. [MARKER: Message] 奧斯卡「",
    "讓我看一下。",
    "5. [MARKER: Message] 奧斯卡「",
    "\\S[8]這就是英國的新兵器……",
    "『伊麗莎白8號』的真面目……。",
    "6. [MARKER: Message] 以藏「",
    "……？",
    "7. [MARKER: Message] 奧斯卡「",
    "不妙啊！！\\.要是這玩意真的啟動了……\\. ",
    "\\S[2]世界可是會毀滅的……。",
    "8. [MARKER: Message] 以藏「",
    "…………！！！？",
    "9. [MARKER: Message] 奧斯卡「",
    "在這傢伙啟動之前，必須想辦法解決它才行……！！",
    "10. [MARKER: Message] 以藏「",
    "直接砸爛它不就得了！！",
    "11. [MARKER: Message] 奧斯卡「",
    "等一下！！這東西被叫作『核彈』，\\. ",
    "如果隨便破壞它，這顆星球的三分之一都會被炸飛……。",
    "12. [MARKER: Message] 以藏「",
    "\\S[2]……………………。\\. ",
    "\\S[1]那，那到底該怎麼辦啊……。",
    "13. [MARKER: Message] 奧斯卡「",
    "能將它解體的，就只有它的製作者了……。",
    "14. [MARKER: Message] 以藏「",
    "\\S[2]到底是誰做的啊……。",
    "15. [MARKER: Message] 奧斯卡「",
    "以前聽我家的女僕提起過……",
    "擁有超越人類智慧的驚人技術力，",
    "異國的賢者——『流漸』！",
    "16. [MARKER: Message] 以藏「",
    "既然如此，我們去拜託那個叫流漸的傢伙，",
    "請他來把這個兵器給拆掉不就行了嘛！！",
    "17. [MARKER: Message] 奧斯卡「",
    "\\S[2]……就是這麼回事。",
    "18. [MARKER: Message] 以藏「",
    "那麼，那傢伙現在人在哪裡呢……。",
    "19. [MARKER: Message] 奧斯卡「",
    "女僕說，他似乎住在一個叫『新日本』的地方。",
    "20. [MARKER: Message] 以藏「",
    "……那是哪裡啊？『新日本』到底是在……。",
    "（雖然我也很在意那個女僕到底是何方神聖就是了）",
    "21. [MARKER: Message] 奧斯卡「",
    "……我也不知道，\\.但是……\\. ",
    "\\S[1]也只能出發去找了……。",
    "22. [MARKER: Message] 以藏「",
    "\\S[2]……。",
    "23. [MARKER: Message] ",
    "　　　　　　　伊麗莎白8號",
    "24. [MARKER: Message] 以藏「",
    "是這個嗎……？",
    "25. [MARKER: Message] 奧斯卡「",
    "讓我看一下。",
    "26. [MARKER: Message] 奧斯卡「",
    "\\S[6]這就是英國的新兵器……",
    "\\S[1]『伊麗莎白8號』的真面目……！！",
    "27. [MARKER: Message] 以藏「",
    "……？",
    "28. [MARKER: Message] 奧斯卡「",
    "\\>不妙啊！！\\<\\.要是這玩意真的啟動了……",
    "\\S[2]世界可是會\\|\\>徹底毀滅的……！\\<",
    "29. [MARKER: Message] 以藏「",
    "…………！！！？",
    "30. [MARKER: Message] 奧斯卡「",
    "在這傢伙啟動之前，必須想辦法解決它才行……！！",
    "31. [MARKER: Message] 以藏「",
    "直接砸爛它不就得了！！",
    "32. [MARKER: Message] 奧斯卡「",
    "等一下！！這東西被叫作『核彈』，\\. ",
    "如果隨便破壞它，這顆星球的三分之一都會被炸飛……。",
    "33. [MARKER: Message] 以藏「",
    "\\S[2]……………………。\\. ",
    "\\S[1]那，那到底該怎麼辦啊……。",
    "34. [MARKER: Message] 奧斯卡「",
    "能將它解體的，就只有它的製作者了……。",
    "35. [MARKER: Message] 以藏「",
    "\\S[2]到底是誰做的啊……。",
    "36. [MARKER: Message] 奧斯卡「",
    "以前聽我家的女僕提起過……",
    "擁有超越人類智慧的驚人技術力，",
    "異國的賢者——『流漸』！",
    "37. [MARKER: Message] 以藏「",
    "既然如此，我們去拜託那個叫流漸的傢伙，",
    "請他來把這個兵器給拆掉不就行了嘛！！",
    "38. [MARKER: Message] 奧斯卡「",
    "\\S[2]……就是這麼回事。",
    "39. [MARKER: Message] 以藏「",
    "那麼，那傢伙現在人在哪裡呢……。",
    "40. [MARKER: Message] 奧斯卡「",
    "女僕說，他似乎住在一個叫『新日本』的地方。",
    "41. [MARKER: Message] 以藏「",
    "……那是哪裡啊？『新日本』到底是在……。",
    "（雖然我也很在意那個女僕到底是何方神聖就是了）",
    "42. [MARKER: Message] 奧斯卡「",
    "……我也不知道，\\.但是……\\. ",
    "\\S[1]也只能出發去找了……。",
    "43. [MARKER: Message] 以藏「",
    "\\S[2]……。",
])

# Map0176 (以藏故鄉與老哥安德烈的對話 - 熱血兄貴大行進)
write_translated("Map0176.txt.trans.txt", [
    "1. [MARKER: Message] [FACE: 主人公2, 10, Left, Normal] 安德烈「",
    "我第一次來到這裡的時候，\\. ",
    "那景象，真的是慘不忍睹……。\\|\\^",
    "2. [MARKER: Message] [FACE: 主人公2, 10, Left, Normal] 安德烈「",
    "你的村子被盜賊團襲擊了……\\. ",
    "只要是膽敢反抗的人，全都慘遭殺害……。\\|\\^",
    "3. [MARKER: Message] [FACE: 主人公2, 10, Left, Normal] 安德烈「",
    "當我趕到的時候，根本就找不到任何的生還者……。\\|\\^",
    "4. [MARKER: Message] [FACE: 主人公2, 10, Left, Normal] 安德烈「",
    "\\S[2]除了你之外呢……。\\|\\^",
    "5. [MARKER: Message] [FACE: Erase] 安德烈「",
    "……孩子？\\. ",
    "居然還有倖存的人嗎！！\\|\\^",
    "6. [MARKER: Message] [FACE: Erase] 少年以藏「",
    "嗚……嗚嗚嗚嗚……！！！",
    "7. [MARKER: Message] [FACE: Erase] 安德烈「",
    "竟然獨自一人熬過了這場慘劇嗎……\\|",
    "不惜將自己化身為了『野獸』……。",
    "8. [MARKER: Message] [FACE: Erase] ",
    "　　　　\\S[2]少年的身邊橫七豎八地躺滿了死屍，\\. ",
    "　　　　 不過那些死屍，全都是盜賊團的人。\\.\\^",
    "9. [MARKER: Message] [FACE: Erase] 安德烈「",
    "然後，現在還想對我也亮出獠牙嗎？\\. ",
    "我並沒有想要傷害你的意思，\\. ",
    "但如果你真的要撲過來，我也不會手下留情的喔。\\|\\^",
    "10. [MARKER: Message] [FACE: Erase] ",
    "安德烈用充滿壓倒性力量的野獸般眼神，盯著眼前的少年。\\|\\^",
    "11. [MARKER: Message] [FACE: Erase] 安德烈「",
    "罷手吧，\\.憑現在的你是贏不了我的。\\|\\^",
    "12. [MARKER: Message] [FACE: Erase] ",
    "　　　　　安德烈靜靜地走向少年，\\. ",
    "　　　　　　溫柔地拿走了他手中的小刀。\\|\\^",
    "13. [MARKER: Message] [FACE: Erase] 安德烈「",
    "你已經無依無靠，變成孤伶伶的一個人了吧？\\|",
    "那麼，要不要跟我一起走？\\|\\^",
    "14. [MARKER: Message] [FACE: Erase] ",
    "　　　　　　　\\S[2]少年靜靜地點了點頭。\\. ",
    "　　 此刻，他的臉上已經再也看不到『野獸』的陰影了。\\|\\^",
    "15. [MARKER: Message] [FACE: Erase] 安德烈「",
    "在那之後，我們就離開了村莊，一路流浪到了凡爾賽。",
    "16. [MARKER: Message] [FACE: Erase] 安德烈「",
    "剛帶你回來的時候，你還真是個讓人頭疼的野孩子呢。\\|",
    "不過但也正是因為那樣，我才覺得更有撫養的價值啊。",
    "17. [MARKER: Message] [FACE: Erase] 以藏「",
    "……。",
    "18. [MARKER: Message] [FACE: Erase] 以藏「",
    "老哥……\\.為什麼老哥當初要救我呢……？",
    "19. [MARKER: Message] [FACE: Erase] 安德烈「",
    "既然到了今天，那我就告訴你吧……。",
    "20. [MARKER: Message] [FACE: Erase] 安德烈「",
    "我曾經是瑪麗・安東妮",
    "所進行的不死研究的實驗體。",
    "21. [MARKER: Message] [FACE: Erase] 安德烈「",
    "瑪麗那傢伙啊，別看她那副樣子，其實進行了",
    "長達 300 年以上的不死研究。\\. ",
    "僅僅是為了不想失去她自己的美貌。",
    "22. [MARKER: Message] [FACE: Erase] 安德烈「",
    "然後在距今大約 100 年前，",
    "開展了通過操控時間與空間，",
    "從而達到不老不死境界的研究。",
    "23. [MARKER: Message] [FACE: Erase] 安德烈「",
    "然而，研究最終以失敗告終，",
    "並沒有研究出完美的物理不死身。",
    "24. [MARKER: Message] [FACE: Erase] 安德烈「",
    "那時，我們這批實驗體本來是要被銷毀的，",
    "但我利用了在實驗中獲得的『空間轉移』能力，",
    "成功逃了出來。",
    "25. [MARKER: Message] [FACE: Erase] 以藏「",
    "\\S[2]我們……？難道說……。",
    "26. [MARKER: Message] [FACE: Erase] 安德烈「",
    "啊啊，除了我之外，當時還有另外一個實驗體。\\. ",
    "那就是『拿破崙』了。",
    "27. [MARKER: Message] [FACE: Erase] 安德烈「",
    "雖然是相同的實驗體，但我並沒有和拿破崙一起逃跑。",
    "因為那時候我還無法熟練地操控『空間轉移』呢。\\. ",
    "28. [MARKER: Message] [FACE: Erase] 安德烈「",
    "所以，我和拿破崙直到前陣子為止，",
    "都完全沒有見過面，也不認識對方。",
    "29. [MARKER: Message] [FACE: Erase] 以藏「",
    "\\S[2]……照這麼說的話……",
    "老哥你現在……到底多少歲了啊……？",
    "30. [MARKER: Message] [FACE: Erase] 安德烈「",
    "不斷重複著『空間轉移』，又被反覆進行實驗的結果，",
    "我現在的年齡大概是 120 歲了吧……。",
    "31. [MARKER: Message] [FACE: Erase] 安德烈「",
    "話雖如此，但我並不想找瑪麗復仇。\\. ",
    "既然得到了超越常人的力量，我就想為了人們",
    "來發揮這份力量。",
    "32. [MARKER: Message] [FACE: Erase] 安德烈「",
    "我在以違背自身意志的方式得到力量時，\\. ",
    "就已經暗自發誓，絕對不會用它來作惡……。",
    "33. [MARKER: Message] [FACE: Erase] 安德烈「",
    "所以，看見因為同樣違背自己意願而變成孤身一人的你，",
    "我就非常想要向你伸出援手……僅此而已喔……。",
    "34. [MARKER: Message] [FACE: Erase] 以藏「",
    "\\S[2]……。",
    "35. [MARKER: Message] [FACE: Erase] 安德烈「",
    "好啦，我是不是有點說得太多了呢……？\\. ",
    "你明天還要起個大早對吧？\\. ",
    "是不是差不多該去睡覺了？",
    "36. [MARKER: Message] [FACE: Erase] 以藏「",
    "我知道了，老哥。",
    "37. [MARKER: Message] [FACE: Erase] 安德烈「",
    "即使相隔兩地，即便我們沒有血緣關係，",
    "你也是我最重要的弟弟喔！",
    "38. [MARKER: Message] [FACE: Erase] 以藏「",
    "在我的心裡，配當我老哥的，\\. ",
    "也就只有安德烈哥哥你一個人而已！！",
    "39. [MARKER: Message] [FACE: Erase] 安德烈「",
    "喔喔，我的好弟弟！！\\. ",
    "遇到困難的時候，隨時都可以叫我！！",
    "40. [MARKER: Message] [FACE: Erase] ",
    "　　　　以藏學會了『熱血兄貴大行進』！！",
    "41. [MARKER: Message] [FACE: Erase] 安德烈「",
    "那麼，\\.代我向科蘿葉女士問好喔！",
    "42. [MARKER: Message] [FACE: Erase] 以藏「",
    "\\S[2]……？\\. 啊，\\.嗯，好的。",
])

# Map0178 (獲得大師神衣)
write_translated("Map0178.txt.trans.txt", [
    "1. [MARKER: Message] ",
    "　　　　　　獲得了大師神衣！！",
])

# Map0180 (裝備與道具合成)
write_translated("Map0180.txt.trans.txt", [
    "1. [MARKER: Message] \\>製作該物品所需材料　　　所需數量　　當前持有數\\.",
    "・回復之札　　　　　　　 ×１０　　　　\\V[43]\\<",
    "2. [MARKER: Message] 決定製作這個嗎？\\!\\^",
    "3. [MARKER: Message] 稍微等我一下喔……。",
    "4. [MARKER: Message] 好嘞，大功告成！",
    "5. [MARKER: Message] ",
    "　　　　　　 獲得了回復之札豪華版！！",
    "6. [MARKER: Message] 製作所需的材料不夠喔。",
    "7. [MARKER: Message] \\>製作該物品所需材料　　　所需數量　　當前持有數\\.",
    "・天龍石　　　　　　　　 ×１０　　　　\\V[43]\\<",
    "8. [MARKER: Message] 決定製作這個嗎？\\!\\^",
    "9. [MARKER: Message] 稍微等我一下喔……。",
    "10. [MARKER: Message] 好嘞，大功告成！",
    "11. [MARKER: Message] ",
    "　　　　　　　獲得了天龍石豪華版！！",
    "12. [MARKER: Message] 製作所需的材料不夠喔。",
    "13. [MARKER: Message] \\>製作該物品所需材料　　　所需數量　　當前持有數\\.",
    "・斬鐵劍　　　　　　　　 ×１　　　　　\\V[43]",
    "・奧里哈魯根之劍　　　　 ×１　　　　　\\V[44]\\<",
    "14. [MARKER: Message] 決定製作這個嗎？\\!\\^",
    "15. [MARKER: Message] 稍微等我一下喔……。",
    "16. [MARKER: Message] 好嘞，大功告成！",
    "17. [MARKER: Message] ",
    "　　　　　　　　　 獲得了超斬鐵劍！！",
    "18. [MARKER: Message] 製作所需的材料不夠喔。",
    "19. [MARKER: Message] 製作所需的材料不夠喔。",
    "20. [MARKER: Message] \\>製作該物品所需材料　　　所需數量　　當前持有數\\.",
    "・超強力馬達　　　　　　 ×１　　　　　\\V[43]",
    "・奧里哈魯根之劍　　　　 ×１　　　　　\\V[44]\\<",
    "21. [MARKER: Message] 決定製作這個嗎？\\!\\^",
    "22. [MARKER: Message] 稍微等我一下喔……。",
    "23. [MARKER: Message] 好嘞，大功告成！",
    "24. [MARKER: Message] ",
    "　　　　　　　　　  獲得了機工斧！！",
    "25. [MARKER: Message] 製作所需的材料不夠喔。",
    "26. [MARKER: Message] 製作所需的材料不夠喔。",
    "27. [MARKER: Message] \\>製作該物品所需材料　　　所需數量　　當前持有數\\.",
    "・水晶匕首　　　　　　　 ×７　　　　　\\V[43]",
    "・水晶研磨機　　　　　　 ×１　　　　　\\V[44]\\<",
    "28. [MARKER: Message] 決定製作這個嗎？\\!\\^",
    "29. [MARKER: Message] 稍微等我一下喔……。",
    "30. [MARKER: Message] 好嘞，大功告成！",
    "31. [MARKER: Message] ",
    "　　　　　　獲得了水晶之刃！！",
    "32. [MARKER: Message] 製作所需的材料不夠喔。",
    "33. [MARKER: Message] 製作所需的材料不夠喔。",
    "34. [MARKER: Message] \\>製作該物品所需材料　　　所需數量　　當前持有數\\.",
    "・戰斧　　　　　　　　　 ×１　　　　　\\V[43]",
    "・電漿噴射推進器　　　　 ×１　　　　　\\V[44]\\<",
    "35. [MARKER: Message] 決定製作這個嗎？\\!\\^",
    "36. [MARKER: Message] 稍微等我一下喔……。",
    "37. [MARKER: Message] 好嘞，大功告成！",
    "38. [MARKER: Message] ",
    "　　　　　　　　　獲得了 ICBM！！",
    "39. [MARKER: Message] 製作所需的材料不夠喔。",
    "40. [MARKER: Message] 製作所需的材料不夠喔。",
    "41. [MARKER: Message] \\>製作該物品所需材料　　　所需數量　　當前持有數\\.",
    "・護盾　　　　　　　　　 ×１　　　　　\\V[43]",
    "・高科技指環　　　　　　 ×１　　　　　\\V[44]\\<",
    "42. [MARKER: Message] 決定製作這個嗎？\\!\\^",
    "43. [MARKER: Message] 稍微等我一下喔……。",
    "44. [MARKER: Message] 好嘞，大功告成！",
    "45. [MARKER: Message] ",
    "　　　　　　 獲得了偉大之盾！！",
    "46. [MARKER: Message] 製作所需的材料不夠喔。",
    "47. [MARKER: Message] 製作所需的材料不夠喔。",
    "48. [MARKER: Message] \\>製作該物品所需材料　　　所需數量　　當前持有數\\.",
    "・水晶研磨機　　　　　　 ×１　　　　　\\V[43]",
    "・紅水晶　　　　　　　　 ×３　　　　　\\V[44]\\<",
    "49. [MARKER: Message] 決定製作這個嗎？\\!\\^",
    "50. [MARKER: Message] 稍微等我一下喔……。",
    "51. [MARKER: Message] 好嘞，大功告成！",
    "52. [MARKER: Message] ",
    "　　　　　 獲得了水晶護盾！！",
    "53. [MARKER: Message] 製作所需的材料不夠喔。",
    "54. [MARKER: Message] 製作所需的材料不夠喔。",
    "55. [MARKER: Message] 你想要做些什麼呢？",
])

print("Map0175-0180 done.")
